### ISSUE TITLE
After upgrading comfyui yesterday(2023/07/16), this plugin cannot be used

### ISSUE THREAD

**Issue by sdqq1234** [WASasquatch/was-node-suite-comfyui#119]
Traceback (most recent call last):
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\ComfyUI\nodes.py", line 1516, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\__init__.py", line 88, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\stencils\stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\registry.py", line 5, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\dispatcher.py", line 13, in <module>
    from numba.core import (
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\compiler.py", line 6, in <module>
    from numba.core import (utils, errors, typing, interpreter, bytecode, postproc,
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\callconv.py", line 13, in <module>
    from numba.core.base import PYOBJECT, GENERIC_POINTER
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\base.py", line 20, in <module>
    from numba.cpython import builtins
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\cpython\builtins.py", line 536, in <module>
    from numba.core.typing.builtins import IndexValue, IndexValueType
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\typing\builtins.py", line 22, in <module>
    @infer_global(print)
  File "E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\python_embeded\lib\site-packages\numba\core\typing\templates.py", line 1271, in register_global
    if getattr(mod, val.__name__) is not val:
AttributeError: module 'E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\ComfyUI\custom_nodes\cup' has no attribute 'wrap'

Cannot import E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: module 'E:\AIProject\ComfyUI_windows0605\ComfyUI_windows\ComfyUI\custom_nodes\cup' has no attribute 'wrap'

**Comment by RuiVuusen** [comment]
this happens to me too

**Comment by WASasquatch** [comment]
Reinstall the requirements, of course.

**Comment by WASasquatch** [comment]
> > 
> 
> I reinstalled, but it didn't work

Then you didn't do it right. Like installing to system python and not your python embedded.

**Comment by sdqq1234** [comment]
> > > 
> > 
> > 
> > I reinstalled, but it didn't work
> 
> Then you didn't do it right. Like installing to system python and not your python embedded.

I reinstalled requirements both on system python and embedded python,but nothing changed, same errors.I think it should be caused by comfyui modifying some codes

**Comment by WASasquatch** [comment]
It's probably the custom node importing it's files via spec or some other method instead of just importing them, thus when ND goes to read the file, those modules aren't loaded at all. Some other nodes require the promptServer which isn't running at all. A lot of custom node authors are writing hacks rather than modules to be imported by larger systems.

**Comment by WASasquatch** [comment]
No, it's cause numba isn't there, meaning it **is not** installed on your ComfyUI portable python in embedded_python/python.exe
