### ISSUE TITLE
Error occurred when executing CLIPTextEncode (NSP): not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by octoworld** [WASasquatch/was-node-suite-comfyui#126]
Error occurring after git pull this morning.

```
WAS Node Suite: CLIPTextEncode Prased Prompt:
 (abstract organic architecture:1.23), Sky blue, James Stokoe
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\somebody\ComfyUI\ComfyUI\execution.py", line 145, in recursive_execute      
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\somebody\ComfyUI\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\somebody\ComfyUI\ComfyUI\execution.py", line 68, in map_node_over_list      
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\somebody\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 8299, in nsp_encode
    embeddings, pooled = clip.encode(new_text)
ValueError: not enough values to unpack (expected 2, got 1)
```
Worked ok before, also all fine swapping it out with default CLIP Text Encode.

**Comment by octoworld** [comment]
Can be resolved by reverting changes in commit 7cc8c03.

**Comment by WASasquatch** [comment]
Should be patched.

**Comment by octoworld** [comment]
confirmed as fixed. cheers.
