### ISSUE TITLE
I'm having an issue installling this

### ISSUE THREAD

**Issue by ninjasaid2k** [WASasquatch/was-node-suite-comfyui#133]
```
C:\Users\*****\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui>pip install -r requirements.txt
Collecting git+https://github.com/WASasquatch/img2texture.git (from -r requirements.txt (line 3))
  Cloning https://github.com/WASasquatch/img2texture.git to c:\users\*****\appdata\local\temp\pip-req-build-x_wvjrrk
  Running command git clone --filter=blob:none --quiet https://github.com/WASasquatch/img2texture.git 'C:\Users\*****\AppData\Local\Temp\pip-req-build-x_wvjrrk'
  Resolved https://github.com/WASasquatch/img2texture.git to commit a546609a915caf1dcb84a15bf44b5b639ad924e6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/WASasquatch/ffmpy.git (from -r requirements.txt (line 12))
  Cloning https://github.com/WASasquatch/ffmpy.git to c:\users\*****\appdata\local\temp\pip-req-build-v8gn5t8f
  Running command git clone --filter=blob:none --quiet https://github.com/WASasquatch/ffmpy.git 'C:\Users\*****\AppData\Local\Temp\pip-req-build-v8gn5t8f'
  Resolved https://github.com/WASasquatch/ffmpy.git to commit f000737698b387ffaeab7cd871b0e9185811230d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cmake (from -r requirements.txt (line 1))
  Using cached cmake-3.27.0-py2.py3-none-win_amd64.whl (34.6 MB)
Collecting fairscale>=0.4.4 (from -r requirements.txt (line 2))
  Using cached fairscale-0.4.13.tar.gz (266 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gitpython (from -r requirements.txt (line 4))
  Using cached GitPython-3.1.32-py3-none-any.whl (188 kB)
Collecting imageio (from -r requirements.txt (line 5))
  Using cached imageio-2.31.1-py3-none-any.whl (313 kB)
Collecting joblib (from -r requirements.txt (line 6))
  Using cached joblib-1.3.1-py3-none-any.whl (301 kB)
Collecting matplotlib (from -r requirements.txt (line 7))
  Using cached matplotlib-3.7.2-cp311-cp311-win_amd64.whl (7.5 MB)
Collecting numba (from -r requirements.txt (line 8))
  Using cached numba-0.57.1-cp311-cp311-win_amd64.whl (2.6 MB)
Collecting numpy<1.24>=1.18 (from -r requirements.txt (line 9))
  Using cached numpy-1.23.5-cp311-cp311-win_amd64.whl (14.6 MB)
Collecting opencv-python-headless[ffmpeg] (from -r requirements.txt (line 10))
  Using cached opencv_python_headless-4.8.0.74-cp37-abi3-win_amd64.whl (38.0 MB)
Collecting pilgram (from -r requirements.txt (line 11))
  Using cached pilgram-1.2.1-py3-none-any.whl (817 kB)
Collecting rembg (from -r requirements.txt (line 13))
  Using cached rembg-2.0.50-py3-none-any.whl (26 kB)
Collecting scikit-image==0.20.0 (from -r requirements.txt (line 14))
  Using cached scikit_image-0.20.0-cp311-cp311-win_amd64.whl (23.7 MB)
Collecting scikit-learn (from -r requirements.txt (line 15))
  Using cached scikit_learn-1.3.0-cp311-cp311-win_amd64.whl (9.2 MB)
Requirement already satisfied: scipy in c:\users\*****\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 16)) (1.11.1)
Collecting timm>=0.4.12 (from -r requirements.txt (line 17))
  Using cached timm-0.9.2-py3-none-any.whl (2.2 MB)
Collecting tqdm (from -r requirements.txt (line 18))
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting transformers==4.26.1 (from -r requirements.txt (line 19))
  Using cached transformers-4.26.1-py3-none-any.whl (6.3 MB)
Collecting networkx>=2.8 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting pillow>=9.0.1 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached Pillow-10.0.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting tifffile>=2019.7.26 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached tifffile-2023.7.18-py3-none-any.whl (221 kB)
Collecting PyWavelets>=1.1.1 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached PyWavelets-1.4.1-cp311-cp311-win_amd64.whl (4.2 MB)
Collecting packaging>=20.0 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting lazy_loader>=0.1 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached lazy_loader-0.3-py3-none-any.whl (9.1 kB)
Collecting filelock (from transformers==4.26.1->-r requirements.txt (line 19))
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting huggingface-hub<1.0,>=0.11.0 (from transformers==4.26.1->-r requirements.txt (line 19))
  Using cached huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
Collecting pyyaml>=5.1 (from transformers==4.26.1->-r requirements.txt (line 19))
  Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
Collecting regex!=2019.12.17 (from transformers==4.26.1->-r requirements.txt (line 19))
  Using cached regex-2023.6.3-cp311-cp311-win_amd64.whl (268 kB)
Collecting requests (from transformers==4.26.1->-r requirements.txt (line 19))
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers==4.26.1->-r requirements.txt (line 19))
  Using cached tokenizers-0.13.3-cp311-cp311-win_amd64.whl (3.5 MB)
Collecting torch>=1.8.0 (from fairscale>=0.4.4->-r requirements.txt (line 2))
  Using cached torch-2.0.1-cp311-cp311-win_amd64.whl (172.3 MB)
Collecting pillow>=9.0.1 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting gitdb<5,>=4.0.1 (from gitpython->-r requirements.txt (line 4))
  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements.txt (line 7))
  Using cached contourpy-1.1.0-cp311-cp311-win_amd64.whl (470 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 7))
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib->-r requirements.txt (line 7))
  Using cached fonttools-4.41.1-cp311-cp311-win_amd64.whl (2.1 MB)
Collecting kiwisolver>=1.0.1 (from matplotlib->-r requirements.txt (line 7))
  Using cached kiwisolver-1.4.4-cp311-cp311-win_amd64.whl (55 kB)
Collecting pyparsing<3.1,>=2.3.1 (from matplotlib->-r requirements.txt (line 7))
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting python-dateutil>=2.7 (from matplotlib->-r requirements.txt (line 7))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting llvmlite<0.41,>=0.40.0dev0 (from numba->-r requirements.txt (line 8))
  Using cached llvmlite-0.40.1-cp311-cp311-win_amd64.whl (27.7 MB)
WARNING: opencv-python-headless 4.8.0.74 does not provide the extra 'ffmpeg'
Collecting onnxruntime (from rembg->-r requirements.txt (line 13))
  Using cached onnxruntime-1.15.1-cp311-cp311-win_amd64.whl (6.7 MB)
Collecting pooch (from rembg->-r requirements.txt (line 13))
  Using cached pooch-1.7.0-py3-none-any.whl (60 kB)
Collecting pymatting (from rembg->-r requirements.txt (line 13))
  Using cached PyMatting-1.1.8-py3-none-any.whl (47 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn->-r requirements.txt (line 15))
  Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Collecting torchvision (from timm>=0.4.12->-r requirements.txt (line 17))
  Using cached torchvision-0.15.2-cp311-cp311-win_amd64.whl (1.2 MB)
Collecting safetensors (from timm>=0.4.12->-r requirements.txt (line 17))
  Using cached safetensors-0.3.1-cp311-cp311-win_amd64.whl (263 kB)
Collecting colorama (from tqdm->-r requirements.txt (line 18))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->-r requirements.txt (line 4))
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting fsspec (from huggingface-hub<1.0,>=0.11.0->transformers==4.26.1->-r requirements.txt (line 19))
  Using cached fsspec-2023.6.0-py3-none-any.whl (163 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub<1.0,>=0.11.0->transformers==4.26.1->-r requirements.txt (line 19))
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 7))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting sympy (from torch>=1.8.0->fairscale>=0.4.4->-r requirements.txt (line 2))
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting jinja2 (from torch>=1.8.0->fairscale>=0.4.4->-r requirements.txt (line 2))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting coloredlogs (from onnxruntime->rembg->-r requirements.txt (line 13))
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting flatbuffers (from onnxruntime->rembg->-r requirements.txt (line 13))
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
INFO: pip is looking at multiple versions of onnxruntime to determine which version is compatible with other requirements. This could take a while.
Collecting onnxruntime (from rembg->-r requirements.txt (line 13))
  Using cached onnxruntime-1.15.0-cp311-cp311-win_amd64.whl (6.7 MB)
Collecting tifffile>=2019.7.26 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached tifffile-2023.7.10-py3-none-any.whl (220 kB)
  Using cached tifffile-2023.7.4-py3-none-any.whl (220 kB)
  Using cached tifffile-2023.4.12-py3-none-any.whl (219 kB)
INFO: pip is looking at multiple versions of onnxruntime to determine which version is compatible with other requirements. This could take a while.
  Using cached tifffile-2023.3.21-py3-none-any.whl (218 kB)
  Using cached tifffile-2023.3.15-py3-none-any.whl (218 kB)
  Using cached tifffile-2023.2.28-py3-none-any.whl (216 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached tifffile-2023.2.27-py3-none-any.whl (216 kB)
  Using cached tifffile-2023.2.3-py3-none-any.whl (215 kB)
  Using cached tifffile-2023.2.2-py3-none-any.whl (214 kB)
  Using cached tifffile-2023.1.23.1-py3-none-any.whl (214 kB)
  Using cached tifffile-2023.1.23-py3-none-any.whl (214 kB)
  Using cached tifffile-2022.10.10-py3-none-any.whl (210 kB)
  Using cached tifffile-2022.8.12-py3-none-any.whl (208 kB)
  Using cached tifffile-2022.8.8-py3-none-any.whl (208 kB)
  Using cached tifffile-2022.8.3-py3-none-any.whl (207 kB)
  Using cached tifffile-2022.7.31-py3-none-any.whl (207 kB)
  Using cached tifffile-2022.7.28-py3-none-any.whl (207 kB)
  Using cached tifffile-2022.5.4-py3-none-any.whl (195 kB)
  Using cached tifffile-2022.4.28-py3-none-any.whl (193 kB)
  Using cached tifffile-2022.4.26-py3-none-any.whl (191 kB)
  Using cached tifffile-2022.4.22-py3-none-any.whl (191 kB)
  Using cached tifffile-2022.4.8-py3-none-any.whl (180 kB)
  Using cached tifffile-2022.3.25-py3-none-any.whl (179 kB)
  Using cached tifffile-2022.3.16-py3-none-any.whl (179 kB)
  Using cached tifffile-2022.2.9-py3-none-any.whl (180 kB)
  Using cached tifffile-2022.2.2-py3-none-any.whl (179 kB)
  Using cached tifffile-2021.11.2-py3-none-any.whl (178 kB)
  Using cached tifffile-2021.10.12-py3-none-any.whl (175 kB)
  Using cached tifffile-2021.10.10-py3-none-any.whl (174 kB)
  Using cached tifffile-2021.8.30-py3-none-any.whl (171 kB)
  Using cached tifffile-2021.8.8-py3-none-any.whl (171 kB)
  Using cached tifffile-2021.7.30-py3-none-any.whl (171 kB)
  Using cached tifffile-2021.7.2-py3-none-any.whl (169 kB)
  Using cached tifffile-2021.6.14-py3-none-any.whl (169 kB)
  Using cached tifffile-2021.6.6-py3-none-any.whl (168 kB)
  Using cached tifffile-2021.4.8-py3-none-any.whl (165 kB)
  Using cached tifffile-2021.3.31-py3-none-any.whl (165 kB)
  Using cached tifffile-2021.3.17-py3-none-any.whl (163 kB)
  Using cached tifffile-2021.3.16-py3-none-any.whl (164 kB)
  Using cached tifffile-2021.3.5-py3-none-any.whl (162 kB)
  Using cached tifffile-2021.3.4-py3-none-any.whl (161 kB)
  Using cached tifffile-2021.2.26-py3-none-any.whl (160 kB)
  Using cached tifffile-2021.2.1-py3-none-any.whl (159 kB)
  Using cached tifffile-2021.1.14-py3-none-any.whl (158 kB)
  Using cached tifffile-2021.1.11-py3-none-any.whl (158 kB)
  Using cached tifffile-2021.1.8-py3-none-any.whl (158 kB)
  Using cached tifffile-2020.12.8-py3-none-any.whl (157 kB)
  Using cached tifffile-2020.12.4-py3-none-any.whl (157 kB)
  Using cached tifffile-2020.11.26-py3-none-any.whl (157 kB)
  Using cached tifffile-2020.11.18-py3-none-any.whl (153 kB)
  Using cached tifffile-2020.10.1-py3-none-any.whl (152 kB)
  Using cached tifffile-2020.9.30-py3-none-any.whl (152 kB)
  Using cached tifffile-2020.9.29-py3-none-any.whl (154 kB)
  Using cached tifffile-2020.9.28-py3-none-any.whl (154 kB)
  Using cached tifffile-2020.9.22-py3-none-any.whl (153 kB)
  Using cached tifffile-2020.9.3-py3-none-any.whl (148 kB)
  Using cached tifffile-2020.8.25-py3-none-any.whl (147 kB)
  Using cached tifffile-2020.8.13-py3-none-any.whl (146 kB)
  Using cached tifffile-2020.7.24-py3-none-any.whl (146 kB)
  Using cached tifffile-2020.7.22-py3-none-any.whl (145 kB)
  Using cached tifffile-2020.7.17-py3-none-any.whl (144 kB)
  Using cached tifffile-2020.7.4-py3-none-any.whl (138 kB)
  Using cached tifffile-2020.6.3-py3-none-any.whl (133 kB)
  Using cached tifffile-2020.5.30-py3-none-any.whl (133 kB)
  Using cached tifffile-2020.5.25-py3-none-any.whl (132 kB)
  Using cached tifffile-2020.5.11-py3-none-any.whl (132 kB)
Collecting imagecodecs>=2020.2.18 (from tifffile>=2019.7.26->scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached imagecodecs-2023.7.10-cp311-cp311-win_amd64.whl (24.3 MB)
Collecting tifffile>=2019.7.26 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached tifffile-2020.5.7-py3-none-any.whl (136 kB)
  Using cached tifffile-2020.5.5-py3-none-any.whl (132 kB)
  Using cached tifffile-2020.2.16-py3-none-any.whl (130 kB)
  Using cached tifffile-2019.7.26.2-py2.py3-none-any.whl (131 kB)
  Using cached tifffile-2019.7.26-py2.py3-none-any.whl (131 kB)
Collecting PyWavelets>=1.1.1 (from scikit-image==0.20.0->-r requirements.txt (line 14))
  Using cached PyWavelets-1.3.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached PyWavelets-1.2.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached PyWavelets-1.1.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements.txt (line 7))
  Using cached contourpy-1.0.7-cp311-cp311-win_amd64.whl (162 kB)
  Using cached contourpy-1.0.6-cp311-cp311-win_amd64.whl (163 kB)
  Using cached contourpy-1.0.5-cp311-cp311-win_amd64.whl (164 kB)
  Using cached contourpy-1.0.4.tar.gz (12.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached contourpy-1.0.3.tar.gz (12.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached contourpy-1.0.2.tar.gz (12.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached contourpy-1.0.1.tar.gz (11.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy (from -r requirements.txt (line 16))
  Using cached scipy-1.11.1-cp311-cp311-win_amd64.whl (44.0 MB)
  Using cached scipy-1.10.1-cp311-cp311-win_amd64.whl (42.2 MB)
  Using cached scipy-1.10.0-cp311-cp311-win_amd64.whl (42.2 MB)
  Using cached scipy-1.9.3-cp311-cp311-win_amd64.whl (39.9 MB)
  Using cached scipy-1.9.2-cp311-cp311-win_amd64.whl (39.9 MB)
  Using cached scipy-1.9.1.tar.gz (42.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: C:\Users\*****\AppData\Local\Temp\pip-install-w61dpn0k\scipy_ea02d044023e45c7a5187311cde750a8
      Build dir: C:\Users\*****\AppData\Local\Temp\pip-install-w61dpn0k\scipy_ea02d044023e45c7a5187311cde750a8\.mesonpy-d86kubg7\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.1
      Activating VS 17.6.4

      ..\..\meson.build:1:0: ERROR: Compiler cl can not compile programs.

      A full log can be found at C:\Users\*****\AppData\Local\Temp\pip-install-w61dpn0k\scipy_ea02d044023e45c7a5187311cde750a8\.mesonpy-d86kubg7\build\meson-logs\meson-log.txt
      + meson setup --native-file=C:\Users\*****\AppData\Local\Temp\pip-install-w61dpn0k\scipy_ea02d044023e45c7a5187311cde750a8\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Users\*****\AppData\Local\Programs\Python\Python311 C:\Users\*****\AppData\Local\Temp\pip-install-w61dpn0k\scipy_ea02d044023e45c7a5187311cde750a8 C:\Users\*****\AppData\Local\Temp\pip-install-w61dpn0k\scipy_ea02d044023e45c7a5187311cde750a8\.mesonpy-d86kubg7\build
      Traceback (most recent call last):
        File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-ka76pj03\overlay\Lib\site-packages\mesonpy\__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-ka76pj03\overlay\Lib\site-packages\mesonpy\__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-ka76pj03\overlay\Lib\site-packages\mesonpy\__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-ka76pj03\overlay\Lib\site-packages\mesonpy\__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-ka76pj03\overlay\Lib\site-packages\mesonpy\__init__.py", line 713, in _configure
          self._meson(
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-ka76pj03\overlay\Lib\site-packages\mesonpy\__init__.py", line 696, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-ka76pj03\overlay\Lib\site-packages\mesonpy\__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=C:\\Users\\*****\\AppData\\Local\\Temp\\pip-install-w61dpn0k\\scipy_ea02d044023e45c7a5187311cde750a8\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=C:\\Users\\*****\\AppData\\Local\\Programs\\Python\\Python311', 'C:\\Users\\*****\\AppData\\Local\\Temp\\pip-install-w61dpn0k\\scipy_ea02d044023e45c7a5187311cde750a8', 'C:\\Users\\*****\\AppData\\Local\\Temp\\pip-install-w61dpn0k\\scipy_ea02d044023e45c7a5187311cde750a8\\.mesonpy-d86kubg7\\build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by WASasquatch** [comment]
Are you using the ComfyUI Windows Portable? Because your installation process is quoting your system python, not the ComfyUI python located in `ComfyUI_windows_portable\python_embeded\python.exe`

There is a `install.bat` you can try inside was-node-suite-comfyui if the [installation instructions](https://github.com/WASasquatch/was-node-suite-comfyui#recommended-installation) are confusing.

**Comment by ninjasaid2k** [comment]
The install.bat ended with this error message:
```
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\ninja\\ComfyUI\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\~umpy\\.libs\\libopenblas64__v0.3.23-gcc_10_3_0.dll'
Consider using the `--user` option or check the permissions.

```

**Comment by WASasquatch** [comment]
It's still seems to be installing stuff to system.  Is your Scripts path in python embedded in your environment PATHS var?  Are you not using the portable ComfyUi? Otherwise you have to compile and build these binaries for your system manually.

**Comment by sborys-ai** [comment]
This error occurs when trying to use the WAS Node Suite in Linux. Spent several days figuring out what the problem was. Turns out, the issue is that the package "scipy-1.9.1.tar.gz" is incompatible with Python versions newer than 3.10, while most recent Linux distributions typically use Python 3.11.x.

The solution is to use Conda to create a virtual environment with a downgraded Python version. Here's how it looks:

conda create -n old_python python=3.10

Then, activate the environment:

conda activate old_python

Next, inside the "/ComfyUI/custom_nodes/was-node-suite-comfyui" directory, run:

pip3 install -r requirements.txt

Also, make sure to run ComfyUI within this environment to use the WAS Node Suite. Before that, run:

pip3 install -r requirements.txt

If you don't need the WAS Node Suite, you can use the base Linux environment with the latest Python version. To do this, run:

conda deactivate.

Enjoy! :)

**Comment by ninjasaid2k** [comment]
> This error occurs when trying to use the WAS Node Suite in Linux. Spent several days figuring out what the problem was. Turns out, the issue is that the package "scipy-1.9.1.tar.gz" is incompatible with Python versions newer than 3.10, while most recent Linux distributions typically use Python 3.11.x.
> 
> The solution is to use Conda to create a virtual environment with a downgraded Python version. Here's how it looks:
> 
> _conda create -n old_python python=3.10_
> 
> Then, activate the environment:
> 
> _conda activate old_python_
> 
> Next, inside the "/ComfyUI/custom_nodes/was-node-suite-comfyui" directory, run:
> 
> _pip3 install -r requirements.txt_
> 
> Also, make sure to run ComfyUI within this environment to use the WAS Node Suite. Before that, run:
> 
> _pip3 install -r requirements.txt_
> 
> If you don't need the WAS Node Suite, you can use the base Linux environment with the latest Python version. To do this, run:
> 
> _conda deactivate_
> 
> Enjoy! :)

Will this work with windows?

**Comment by sborys-ai** [comment]
I think yes, to do this, you need to install Conda for Windows. 

_https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html_

The commands may vary, but the principle remains the same.

**Comment by WASasquatch** [comment]
This is a common issue installing to system Python on Windows, without having the build tools to do so. ComfyUI Portable ships with these tools you need. I don't support manual installations because that means supporting various compilation and building method on various OSes, which even changes on different systems and software versions. Just a hassle.
