### ISSUE TITLE
No module named 'numba' 

### ISSUE THREAD

**Issue by wzgrx** [WASasquatch/was-node-suite-comfyui#141]
winds
### ComfyUI Revision: 1216 [fbf5c51c]
Traceback (most recent call last):
  File "G:\Soft\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Soft\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "G:\Soft\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import G:\Soft\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: No module named 'numba'

**Comment by WASasquatch** [comment]
Did you install through manager or manually? Numba is the most common issue and there a lot of topics regarding it you can look for. The usual culprit is not installing WAS-NS to ComfyUI's portable. Outside portable you need to compile and build the wheels yourself.
