### ISSUE TITLE
How to install plugins in portable comfyui?

### ISSUE THREAD

**Issue by wzgrx** [WASasquatch/was-node-suite-comfyui#153]
path/to/ComfUI/python_embeded/python.exe -s -m pip install -r requirements.txt

PS G:\ComfyUI_windows_portable> path/to/ComfUI/python_embeded/python.exe -s -m pip install -r requirements.txt
path/to/ComfUI/python_embeded/python.exe : 无法将“path/to/ComfUI/python_embeded/python.exe”项识别为 cmdlet、函数、脚
本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ path/to/ComfUI/python_embeded/python.exe -s -m pip install -r require ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (path/to/ComfUI/python_embeded/python.exe:String) [], CommandNotFoundExc
   eption
    + FullyQualifiedErrorId : CommandNotFoundException

PS G:\ComfyUI_windows_portable>

**Comment by wzgrx** [comment]
G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
G:\ComfyUI_windows_portable\ComfyUI\web\extensions\failfast-comfyui-extensions
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1604, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\SDXLCustomAspectRatio\\__init__.py'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLCustomAspectRatio module for custom nodes: [Errno 2] No such file or directory: 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\SDXLCustomAspectRatio\\__init__.py'
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM cudaMallocAsync
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1604, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: No module named 'numba'
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1604, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Node_Suite.py module for custom nodes: No module named 'numba'

**Comment by WASasquatch** [comment]
Seems like you have a few nodes not working correctly. Have you tried installing with ConfyUI Manager plugin?  If you are using portable you need to use the full path to the requirements file so it can find it, since you were running from within the python embedded folder.

**Comment by kaliumlive** [comment]
how would i  do the full path thing for the requirements file?

**Comment by WASasquatch** [comment]
Same as above, with full path to the requirements file.
