### ISSUE TITLE
Error in New Update process

### ISSUE THREAD

**Issue by Piscabo** [WASasquatch/was-node-suite-comfyui#178]
** ComfyUI start up time: 2023-08-23 21:03:45.173928

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

## Execute install/(de)activation script for 'A:\AI_Files\ComfyUI\custom_nodes\was-node-suite-comfyui'
 Collecting git+https://github.com/WASasquatch/img2texture.git
   Cloning https://github.com/WASasquatch/img2texture.git to c:\users\**\appdata\local\temp\pip-req-build-5ueq_jfs
[!]   Running command git clone --filter=blob:none --quiet https://github.com/WASasquatch/img2texture.git 'C:\Users\**\AppData\Local\Temp\pip-req-build-5ueq_jfs'
   Resolved https://github.com/WASasquatch/img2texture.git to commit a546609a915caf1dcb84a15bf44b5b639ad924e6
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [35 lines of output]
[!]   A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\setuptools\dist.py:804: SetuptoolsDeprecationWarning: Deprecated API usage.
[!]   !!
[!]
[!]           ********************************************************************************
[!]           As setuptools moves its configuration towards `pyproject.toml`,
[!]           `setuptools.config.parse_configuration` became deprecated.
[!]
[!]           For the time being, you can use the `setuptools.config.setupcfg` module
[!]           to access a backward compatible API, but this module is provisional
[!]           and might be removed in the future.
[!]
[!]           To read project metadata, consider using
[!]           ``build.util.project_wheel_metadata`` (https://pypi.org/project/build/).
[!]           For simple scenarios, you can also try parsing the file directly
[!]           with the help of ``configparser``.
[!]           ********************************************************************************
[!]
[!]   !!
[!]     parse_configuration(
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\**\AppData\Local\Temp\pip-req-build-5ueq_jfs\setup.py", line 22, in <module>
[!]       setup(
[!]     File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\setuptools\__init__.py", line 154, in setup
[!]       _install_setup_requires(attrs)
[!]     File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\setuptools\__init__.py", line 146, in _install_setup_requires
[!]       dist.parse_config_files(ignore_option_errors=True)
[!]     File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\setuptools\dist.py", line 804, in parse_config_files
[!]       parse_configuration(
[!]     File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\setuptools\config\__init__.py", line 36, in _wrapper
[!]       return fn(*args, **kwargs)
[!]     File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\setuptools\config\setupcfg.py", line 190, in parse_configuration
[!]       distribution._referenced_files.update(
[!]   AttributeError: 'MinimalDistribution' object has no attribute '_referenced_files'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: A:\AI_Files\ComfyUI\custom_nodes\was-node-suite-comfyui

**Comment by WASasquatch** [comment]
Are you using Python 3.11? It may not be supported. It's a old piece of software. Additionally if you are not using ComfyUI Portable version you won't have the necessary build tools installed and will need to install all that yourself and compile dependencies

**Comment by Piscabo** [comment]
> Are you using Python 3.11? It may not be supported. It's a old piece of software. Additionally if you are not using ComfyUI Portable version you won't have the necessary build tools installed and will need to install all that yourself and compile dependencies

Been in the game for a while, so I know that P3.11 does not work with Comfy, and I'm using venv. So is this the build tools you are referring to? "pip install build" (build 0.10.0)

**Comment by WASasquatch** [comment]
Maybe try older versions of setuptools like the June release: https://pypi.org/project/setuptools/#history
