### ISSUE TITLE
I had to reinstall because of some system upgrades.. Suites unable to load now

### ISSUE THREAD

**Issue by s-marcelle** [WASasquatch/was-node-suite-comfyui#183]
I have no ideas what's going on because that module was necessary for some other nodes so its installed.

I am running the standalone version of ComfyUI
```
Traceback (most recent call last):
  File "C:\Users\sherw\ComfyUI_\ComfyUI\nodes.py", line 1694, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\PPF_Noise_ComfyUI\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\PPF_Noise_ComfyUI\nodes.py", line 4, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'
```

**Comment by WASasquatch** [comment]
Run the requirements against your python_embeded/python.exe if you're using the standalone portable. 

`C:\Users\sherw\ComfyUI_\python_embeded\python.exe -s -m pip install -r C:\Users\sherw\ComfyUI_\ComfyUI\custom_nodes\PPF_Noise_ComfyUI\requirements.txt`

**Comment by WASasquatch** [comment]
Didn't mean to close it. Wrong button. Lol

**Comment by nlienard** [comment]
got same error

running 

```

C:\Users\nico\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui>C:\Users\nico\IA\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install -r requirements.txt
```

end with : 

```
Installing collected packages: numpy, llvmlite, joblib, img2texture, humanfriendly, pooch, pilgram, opencv-python-headless, numba, coloredlogs, transformers, scikit-learn, scikit-image, pymatting, fairscale, rembg
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
  Attempting uninstall: transformers
    Found existing installation: transformers 4.32.1
    Uninstalling transformers-4.32.1:
      Successfully uninstalled transformers-4.32.1
  Attempting uninstall: scikit-image
    Found existing installation: scikit-image 0.21.0
    Uninstalling scikit-image-0.21.0:
      Successfully uninstalled scikit-image-0.21.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fvcore 0.1.5.post20221221 requires tabulate, which is not installed.
Successfully installed coloredlogs-15.0.1 fairscale-0.4.13 humanfriendly-10.0 img2texture-1.0.6 joblib-1.3.2 llvmlite-0.40.1 numba-0.57.1 numpy-1.23.5 opencv-python-headless-4.7.0.72 pilgram-1.2.1 pooch-1.7.0 pymatting-1.1.8 rembg-2.0.50 scikit-image-0.20.0 scikit-learn-1.3.0 transformers-4.26.1


```

**Comment by nlienard** [comment]
but nothing works:

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/13884545/d0c50c7f-8557-4f51-9100-509045d0f68d)

**Comment by nlienard** [comment]
When running update i got this err

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/13884545/cf394825-428a-4645-ae3c-88030bf11493)

**Comment by nlienard** [comment]
well it works now thanks
