### ISSUE TITLE
Image save - Save in other HDD causes odd error

### ISSUE THREAD

**Issue by Ferniclestix** [WASasquatch/was-node-suite-comfyui#190]
AS above, - it does succeed, but it throws this in console.

Error handling request
Traceback (most recent call last):
  File "D:\othercomfy\origin\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\ComfyUI\server.py", line 270, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
  File "ntpath.py", line 804, in commonpath
ValueError: Paths don't have the same drive
Error handling request
Traceback (most recent call last):
  File "D:\othercomfy\origin\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\othercomfy\origin\ComfyUI_windows_portable\ComfyUI\server.py", line 270, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
  File "ntpath.py", line 804, in commonpath
ValueError: Paths don't have the same drive

This gets triggered when I save to a different harddrive using WAS 'image save' node, only time it happens

Absolutely mystifies me.  Unsure if it originates in WAS or not, but seeing as thats what triggers it. figured I might point it out.

**Comment by WASasquatch** [comment]
ComfyUI doesn't support external paths not mounted to the server.  So preview images only work on ComfyUI dirs. Add the path launch arguments.
