### ISSUE TITLE
SDXL Support for KSAMPLER (Cycle)

### ISSUE THREAD

**Issue by TripleHeadedMonkey** [WASasquatch/was-node-suite-comfyui#195]
This is more of a question than anything else.

!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 8630, in sample
    positive = comb.addWeighted(pos_additive, positive, pos_strength)[0]
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 97, in addWeighted
    tw = torch.mul(t1, conditioning_to_strength) + torch.mul(t0, (1.0 - conditioning_to_strength))
RuntimeError: The size of tensor a (1280) must match the size of tensor b (2048) at non-singleton dimension 2

Getting this error when running the KSampler (cycle) with SDXL. This indicates that an SD1.5 model or resource is being used within this node. Is there some way you could release an updated version of this node which does not contain whatever feature that can't be used with SDXL models?

I would very much like to try including this version of the sampler in my workflows, but am finding it impossible without redownloading SD1.5 models I got rid of a month ago.

**Comment by WASasquatch** [comment]
It works fine for SDXL, you just can't mix model types since your conditioning it only for one.
