### ISSUE TITLE
Input failed after updating comfyui

### ISSUE THREAD

**Issue by knowknow0** [WASasquatch/was-node-suite-comfyui#203]
Downloading anime face detector...
Failed to download lbpcascade_animeface.xml so please download it yourself.
Searge-SDXL v4.1 in D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
Traceback (most recent call last):
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib.bootstrap>", line 241, in call_with_frames_removed
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui_init.py", line 1, in <module>
from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
from numba import jit
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\numba_init.py", line 55, in <module>
ensure_critical_deps()
File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\numba_init.py", line 42, in _ensure_critical_deps
raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less

Cannot import D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: Numba needs NumPy 1.24 or less

0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

**Comment by WASasquatch** [comment]
Reinstall WAS-NS requirements.

**Comment by knowknow0** [comment]
> Reinstall WAS-NS requirements.

I've actually tried multiple ways to reinstall the requirements. But it still reports an error, but I've fixed it now.
I downloaded the old version of the UI and pasted the python_embedded folder into the new version

Thank you very much for your reply!
