### ISSUE TITLE
WAS Node Suite Error: Unable to save file due to the to the following error: Extra data: line 1186 column 2 (char 74515)

### ISSUE THREAD

**Issue by p0mad** [WASasquatch/was-node-suite-comfyui#206]
I get the following Errors!

WAS Node Suite Error: Unable to save file due to the to the following error:
Expecting ',' delimiter: line 637 column 59 (char 40169)

WAS Node Suite Error: Unable to save file due to the to the following error:
Extra data: line 1186 column 2 (char 74515)

It was ok saving images for about 160 of generated image. but after that i see this error while it saves the image!!!
i'm not sure if it affects the saved image or not!

**Comment by p0mad** [comment]
Now, when i stoped the server, and start it again this error shown:
FETCH DATA from: D:\sl\win\Control\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "D:\sl\mamba\envs\PSL\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\sl\mamba\envs\PSL\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\sl\mamba\envs\PSL\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\sl\win\Control\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\sl\win\Control\server.py", line 416, in get_object_info
    out[x] = node_info(x)
  File "D:\sl\win\Control\server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\sl\win\Control\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5078, in INPUT_TYPES     
    HDB = WASDatabase(WAS_HISTORY_DATABASE)
  File "D:\sl\win\Control\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 735, in __init__
    self.data = json.load(f)
  File "D:\sl\mamba\envs\PSL\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\sl\mamba\envs\PSL\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\sl\mamba\envs\PSL\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1186 column 2 (char 74515)

**Comment by WASasquatch** [comment]
Your database has been altered incorrectly. May have edited manually and saved in wrong encoding or added wrong syntax.  Line 1186, columns 2

**Comment by p0mad** [comment]
can you guide me to fix it?
@WASasquatch

**Comment by WASasquatch** [comment]
I don't know what the issue is. Something at that line. If there is nothing in there you need to save you could delete it and let suite generate a new one.

**Comment by p0mad** [comment]
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/131435526/757658bf-8b79-4a9e-8df2-6a0a1d76bc14)

**Comment by p0mad** [comment]
@WASasquatch 
its Empty
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/131435526/a9754a16-3674-42ea-baa6-6ca9a13b3b5c)


and my workflow does not even have a VideoWriter !

**Comment by p0mad** [comment]
@WASasquatch 

I'm not sure why!

but it automatically added two " } } "  in the history file!!!

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/131435526/da34b72f-1ba7-4ae6-b528-a2b5726ca73a)


after removing those, the error gone!

**Comment by p0mad** [comment]
I guess its because of the number of generated images!
@WASasquatch 
Are there any limit?
I'm sure it got added automatically because that happened during a long generation

**Comment by WASasquatch** [comment]
I haven't experienced this and have processed entire movies or frames.

**Comment by p0mad** [comment]
each time when it reaches about 1100 logs, i need to manually clean the logs for the other run!
I'm not sure why you dont reproduce such behaivor ... but i'm using CNs, ...

and also my frames are about 200 for each clip .. then it rests for the next clip ... and about 1100 this error appears!

**Comment by YacratesWyh** [comment]
Same error experienced!
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/8447769/cba5f030-3240-4b65-ad42-058a687c02cd)

**Comment by WASasquatch** [comment]
Your file has grown too big, and wasn't saved before being loaded/edited
again by another process. So you have to repair the file or delete it.

**Comment by juansnchz3** [comment]
Deleting the file works for me 👍
