### ISSUE TITLE
No module named 'models.blip' 

### ISSUE THREAD

**Issue by sanshaoyeyang** [WASasquatch/was-node-suite-comfyui#210]
cant run the blip loader node!please help

!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 10581, in blip_model
    from models.blip import blip_decoder
ModuleNotFoundError: No module named 'models.blip'

**Comment by WASasquatch** [comment]
Are you using the BLIP Model Loader? I think I forgot to append the repo path. https://github.com/WASasquatch/was-node-suite-comfyui/commit/573464e4ff27b88a0a48f7a5d977b47672d01c97

**Comment by sanshaoyeyang** [comment]
> 您使用的是 BLIP 模型加载器吗？我想我忘记附加存储库路径。[573464e](https://github.com/WASasquatch/was-node-suite-comfyui/commit/573464e4ff27b88a0a48f7a5d977b47672d01c97)

Sorry for not logging in and replying to you in a timely manner in the past two days. Thank you for your reply.
Yes, I encountered the above issue while using the BLIP model loader you mentioned. After adding the code according to your reply, the result remains the same and did not solve the problem. I found an error when installing requirements.txt in the BLIP folder. I suspect this issue may be the cause, but I am unable to resolve it.
<img width="727" alt="image" src="https://github.com/WASasquatch/was-node-suite-comfyui/assets/30750058/45fa0eda-9833-4414-bad6-5ef37cb2d551">

**Comment by WASasquatch** [comment]
I am not familiar with tokenizers install or TOML installations, I may not
be of much help but I will look into it as soon as possible.

**Comment by liangkun43** [comment]
After I installed the "[Comfyui Lama](https://github.com/hhhzzyang/Comfyui_Lama)" node, my latest WAS node also received the same error. Another node, "[Comfy Clip Blip Node](https://github.com/paulo-coronado/comfy_clip_blip_node)" also received the same error, but when I used this [version](https://github.com/seanlynch/comfy_clip_blip_node/tree/fix-paths), the problem was resolved.WAS node still received this error
![微信截图_20231005004630](https://github.com/WASasquatch/was-node-suite-comfyui/assets/135417715/c828a2f0-e884-4abc-ae29-ba0c4fdf3478)

**Comment by WASasquatch** [comment]
Probably a fair bet you should not have two nodes trying to import the same namespaces if you don't want conflicts.

**Comment by liangkun43** [comment]
I uninstalled "Comfy Clip Blip Node" and transformers, and reinstalled WAS node, but still received this error.
![微信截图_20231005113633](https://github.com/WASasquatch/was-node-suite-comfyui/assets/135417715/357dcdbf-2f84-49ce-8e2e-93f35e27eade)
![微信截图_20231005113659](https://github.com/WASasquatch/was-node-suite-comfyui/assets/135417715/83e23c06-d29a-404b-9db6-473e568905ef)

**Comment by WASasquatch** [comment]
Does the repo even exist under was-node-suite-comfyui/repos/BLIP? All it's
doing is appending the path and importing as normal. So any issue with
would be confliction or just not there.

**Comment by liangkun43** [comment]
Is it related to this  [issue](https://github.com/paulo-coronado/comfy_clip_blip_node/pull/3)?

**Comment by WASasquatch** [comment]
> Is it related to this [issue](https://github.com/paulo-coronado/comfy_clip_blip_node/pull/3)?

No, that's just a PR to change things, which would likely also break BLIP because BLIP must be imported relative, as it itself uses local imports. So if you just import it from anywhere it can't import it's resources and will error out, cause it's not part of its package namespace

**Comment by WASasquatch** [comment]
Alright so BLIP is now a shipped module of WAS-NS. It doesn't need to download the repo or use it with sys.path.append
