### ISSUE TITLE
Hello, big guys, I want to ask the node installed, but can not be loaded in the workflow, because what

### ISSUE THREAD

**Issue by xiaoyangma2008** [WASasquatch/was-node-suite-comfyui#217]

**Comment by WASasquatch** [comment]
If the workflow isn't loading there is an issue, yes. But what I couldn't say without an error log.

**Comment by the2ndface** [comment]
Registered sys.path: ['/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/home/ubuntu/ComfyUI/custom_nodes/comfy_PoP/comfy', '/home/ubuntu/ComfyUI/custom_nodes/comfy_PoP/comfy', '/home/ubuntu/ComfyUI/comfy', '/usr/local/lib/python3.8/dist-packages/git/ext/gitdb', '/home/ubuntu/ComfyUI', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/ubuntu/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/local/lib/python3.8/dist-packages/cloud_init-20.1-py3.8.egg', '/usr/lib/python3/dist-packages', '/tmp/tmppf_ucxzb', '../..']
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 5693
    match background_color:
          ^
SyntaxError: invalid syntax

Cannot import /home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui module for custom nodes: invalid syntax (WAS_Node_Suite.py, line 5693)

**Comment by WASasquatch** [comment]
Thanks for the error. I'll take a look, but very strange you would have a
syntax error. Did you edit WAS-NS? A syntax error would be erroring
everyone out including me.

**Comment by WASasquatch** [comment]
So this is because `match` statement is for Python 3.10 and higher. I have patched this code so it should run on older versions now.

**Comment by WASasquatch** [comment]
Have you tested the latest patch to see if it's working on your ubuntu dist? If there are further compatibility issues please let me know and I was rectify them.
