### ISSUE TITLE
This error will be reported every time it is started，

### ISSUE THREAD

**Issue by the2ndface** [WASasquatch/was-node-suite-comfyui#219]
WAS Node Suite Error: OpenCV Python module still cannot be imported. There is a system conflict.
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 4, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Cannot import /home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux module for custom nodes: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by WASasquatch** [comment]
Please report the error to control net aux custom node. This is not my repos error.
