### ISSUE TITLE
Error occurred when executing Bounded Image Blend with Mask:

### ISSUE THREAD

**Issue by YuQiQAQ** [WASasquatch/was-node-suite-comfyui#238]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WAS_Bounded_Image_Blend_With_Mask.bounded_image_blend_with_mask() got an unexpected keyword argument 'blend_factor'

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/102429252/82643dac-e95e-4e83-8615-67d964179784)

**Comment by YuQiQAQ** [comment]
Hello, I found that the plug-in was just updated today, so I tried the node again, and I found that it still didn't work and reported an error that the 'image' parameter could not be found. So I checked the BOUNDED IMAGE BLEND WITH MASK code of WAS_Node_Suite.py, and I found that you have changed it, But it still has a simple problem.
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/102429252/c0e03d5c-252a-4580-8862-4531c3935360)
So I modified it and now it works, thanks for your the working 😊
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/102429252/be3ccf7c-fa65-4b4e-be23-24533ec008d7)

**Comment by WASasquatch** [comment]
It still doesn't have batch support, though.
