### ISSUE TITLE
Image Save

### ISSUE THREAD

**Issue by alexbofa** [WASasquatch/was-node-suite-comfyui#252]
Hello I have problem, I use [same workflow](https://github.com/WASasquatch/was-node-suite-comfyui/issues/220#issuecomment-1741430609) with other nodes:
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/58225118/d79a03fb-3d6e-4684-8f16-1e8dc5c9c1bb)

```bat
Loading 2 new models
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [25:16<00:00, 43.33s/it]
WAS Node Suite: 00001 Index: 1
WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
Prompt executed in 1607.32 seconds
Error handling request
Traceback (most recent call last):
  File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "X:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "X:\ComfyUI\ComfyUI\server.py", line 270, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
  File "ntpath.py", line 804, in commonpath
ValueError: Paths don't have the same drive
Error handling request
Traceback (most recent call last):
  File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "X:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "X:\ComfyUI\ComfyUI\server.py", line 270, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
  File "ntpath.py", line 804, in commonpath
ValueError: Paths don't have the same drive
```

Why don't other images want to be saved?

**Comment by alexbofa** [comment]
```bat
WAS Node Suite: 00001 Index: 1
WAS Node Suite: 00001 Index: 1
100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.37it/s]
Prompt executed in 11.87 seconds
Prompt executor has been patched by Job Iterator!
WAS Node Suite: 00001 Index: 1
WAS Node Suite: 00001 Index: 1
100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.36it/s]
Prompt executed in 11.93 seconds
Prompt executor has been patched by Job Iterator!
WAS Node Suite: 00001 Index: 1
WAS Node Suite: 00001 Index: 1
100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.43it/s]
Prompt executed in 11.65 seconds
Prompt executor has been patched by Job Iterator!
WAS Node Suite: 00001 Index: 1
WAS Node Suite: 00001 Index: 1
100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.42it/s]
Prompt executed in 11.65 seconds
Prompt executor has been patched by Job Iterator!
WAS Node Suite: 00001 Index: 1
WAS Node Suite: 00001 Index: 1
100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.36it/s]
```

I don't know why, but I only started rendering the frame 00001

I think problem in these nodes 
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/58225118/603cc636-a579-4deb-89e1-ff5070768c97)

**Comment by WASasquatch** [comment]
> ```batchfile
> WAS Node Suite: 00001 Index: 1
> WAS Node Suite: 00001 Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.37it/s]
> Prompt executed in 11.87 seconds
> Prompt executor has been patched by Job Iterator!
> WAS Node Suite: 00001 Index: 1
> WAS Node Suite: 00001 Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.36it/s]
> Prompt executed in 11.93 seconds
> Prompt executor has been patched by Job Iterator!
> WAS Node Suite: 00001 Index: 1
> WAS Node Suite: 00001 Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.43it/s]
> Prompt executed in 11.65 seconds
> Prompt executor has been patched by Job Iterator!
> WAS Node Suite: 00001 Index: 1
> WAS Node Suite: 00001 Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.42it/s]
> Prompt executed in 11.65 seconds
> Prompt executor has been patched by Job Iterator!
> WAS Node Suite: 00001 Index: 1
> WAS Node Suite: 00001 Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.36it/s]
> ```
> 
> I don't know why, but I only started rendering the frame 00001
> 
> ```batchfile
> Prompt executed in 11.76 seconds
> Prompt executor has been patched by Job Iterator!
> WAS Node Suite:  Index: 1
> WAS Node Suite:  Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.26it/s]
> Prompt executed in 12.07 seconds
> Prompt executor has been patched by Job Iterator!
> WAS Node Suite:  Index: 1
> WAS Node Suite:  Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.44it/s]
> Prompt executed in 11.46 seconds
> Prompt executor has been patched by Job Iterator!
> WAS Node Suite:  Index: 1
> WAS Node Suite:  Index: 1
> 100%|████████████████████████████████████████████████████████████| 35/35 [00:10<00:00,  3.35it/s]
> Prompt executed in 11.64 seconds
> ```
> 
> I think problem in [masquerade-nodes](https://github.com/BadCafeCode/masquerade-nodes-comfyui) **Cut by mask**, but what can break the previous nodes? ![image](https://user-images.githubusercontent.com/58225118/278263661-e8f4ee02-ff06-4e56-ac91-8f7b862afc48.png)

Prompt execution being patched may be preventing proper iterations of prompt queue. 



> Hello I have problem, I use [same workflow](https://github.com/WASasquatch/was-node-suite-comfyui/issues/220#issuecomment-1741430609) with other nodes: ![image](https://user-images.githubusercontent.com/58225118/278091869-d79a03fb-3d6e-4684-8f16-1e8dc5c9c1bb.png)
> 
> ```batchfile
> Loading 2 new models
> 100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [25:16<00:00, 43.33s/it]
> WAS Node Suite: 00001 Index: 1
> WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
> WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
> WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
> WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
> WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
> WAS Node Suite: Image file saved to: X:\out\img2img_upscale_key\00001.png
> Prompt executed in 1607.32 seconds
> Error handling request
> Traceback (most recent call last):
>   File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
>     resp = await request_handler(request)
>   File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
>     resp = await handler(request)
>   File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "X:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
>     response: web.Response = await handler(request)
>   File "X:\ComfyUI\ComfyUI\server.py", line 270, in view_image
>     if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
>   File "ntpath.py", line 804, in commonpath
> ValueError: Paths don't have the same drive
> Error handling request
> Traceback (most recent call last):
>   File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
>     resp = await request_handler(request)
>   File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
>     resp = await handler(request)
>   File "X:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "X:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
>     response: web.Response = await handler(request)
>   File "X:\ComfyUI\ComfyUI\server.py", line 270, in view_image
>     if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
>   File "ntpath.py", line 804, in commonpath
> ValueError: Paths don't have the same drive
> ```
> 
> Why don't other images want to be saved?

It seems Comfy is trying to enforce images to be on the same drive and in output for now, from what I gather. Which is not cool.

**Comment by alexbofa** [comment]
This workflow also worked before, now the same problem.

![Screen-2671](https://github.com/WASasquatch/was-node-suite-comfyui/assets/58225118/09779b51-3cd1-40b4-9269-40c79242ba64)

```bat
Prompt executed in 4.38 seconds
WAS Node Suite: 00001 Index: 2
Prompt executed in 3.03 seconds
WAS Node Suite: 00001 Index: 3
Prompt executed in 2.64 seconds
WAS Node Suite: 00001 Index: 4
Prompt executed in 2.86 seconds
WAS Node Suite: 00001 Index: 5
Prompt executed in 2.64 seconds
WAS Node Suite: 00001 Index: 6
Prompt executed in 2.66 seconds
WAS Node Suite: 00001 Index: 7
Prompt executed in 2.65 seconds
WAS Node Suite: 00001 Index: 8
Prompt executed in 2.68 seconds
WAS Node Suite: 00001 Index: 9
Prompt executed in 2.66 seconds
WAS Node Suite: 00001 Index: 10
Prompt executed in 2.64 seconds
WAS Node Suite: 00001 Index: 11
Prompt executed in 2.65 seconds
WAS Node Suite: 00001 Index: 12
Prompt executed in 2.66 seconds
WAS Node Suite: 00001 Index: 13
Prompt executed in 2.65 seconds
WAS Node Suite: 00001 Index: 14
Prompt executed in 2.85 seconds
WAS Node Suite: 00001 Index: 15
Prompt executed in 2.69 seconds
WAS Node Suite: 00001 Index: 16
Prompt executed in 2.96 seconds
WAS Node Suite: 00001 Index: 17
Prompt executed in 2.82 seconds
WAS Node Suite: 00001 Index: 18
Prompt executed in 2.82 seconds
WAS Node Suite: 00001 Index: 19
Prompt executed in 2.74 seconds
WAS Node Suite: 00001 Index: 20
Prompt executed in 2.68 seconds
WAS Node Suite: 00001 Index: 21
Prompt executed in 2.73 seconds
WAS Node Suite: 00001 Index: 22
Prompt executed in 2.77 seconds
WAS Node Suite: 00001 Index: 0
Prompt executed in 2.78 seconds
```

**Comment by WASasquatch** [comment]
I am not sure that the issue is. All my nodes send is a IMAGE tensor. It
sounds like this problem is with ComfyUI. Perhaps a script you have
installed.

**Comment by alexbofa** [comment]
so far, but I don't understand the problem, while I'm writing what I know. I don't know where to turn yet and how to solve it)

**Comment by WASasquatch** [comment]
Can you check your browser console log for script errors with the front
end? Maybe there is something there I can pass along to comfy.

**Comment by alexbofa** [comment]
This console?
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/58225118/37cd7d99-0375-49d6-b785-d364416c2ab0)

**Comment by alexbofa** [comment]
Hm, что делать в данном случае, кому писать, как исправлять?

Так как в **run_nvidia_gpu.bat** прописан `--output-directory` например `X:\Stable-Diffusion\output\ComfyUI`, а сохраняю другие проекты в `X:\Stable-Diffusion\output\Projects` из-за этого конфликт? Ещё этот путь это символическая ссылка `X:\Stable-Diffusion\output` так как из этой папки картинки закидываются на облачный диск.

**Comment by alexbofa** [comment]
Hm, what should I do in this case, who should I write to, how should I fix it?

Since `--output-directory` is written in **run_nvidia_gpu.bat** for example `X:\Stable-Diffusion\output\ComfyUI `, and I save other projects in `X:\Stable-Diffusion\output\Projects` is there a conflict over this? Also this path is a symlink `X:\Stable-Diffusion\output ` since images are uploaded from this folder to the cloud drive.

**Comment by WASasquatch** [comment]
It may be the symlinks, as I have my output directory on D, while portable
is on C drive.
