### ISSUE TITLE
No module named 'midas.dpt_depth' - shadowed?

### ISSUE THREAD

**Issue by picobyte** [WASasquatch/was-node-suite-comfyui#268]
Since my update comyUI all update, yesterday, I'm getting errors on a previously working worksheet.

It started in [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux/issues/108), that also had recent midas updates, and now was follows suit:
```
Error occurred when executing MiDaS Model Loader:

No module named 'midas.dpt_depth'

File "ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 8462, in load_midas_model
midas = torch.hub.load("intel-isl/MiDaS", midas_model, trust_repo=True)
File "stable-diffusion-webui/venv310cu118/lib/python3.10/site-packages/torch/hub.py", line 566, in load
model = _load_local(repo_or_dir, model, *args, **kwargs)
File "stable-diffusion-webui/venv310cu118/lib/python3.10/site-packages/torch/hub.py", line 592, in _load_local
hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
File "stable-diffusion-webui/venv310cu118/lib/python3.10/site-packages/torch/hub.py", line 106, in _import_module
spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "ComfyUI/models/midas/intel-isl_MiDaS_master/hubconf.py", line 5, in
from midas.dpt_depth import DPTDepthModel
```
ComfyUI and stable-diffusion-webui are listed, but this is because the ComfyUI venv is a symlink to the table-diffusion-webui, which worked just fine for me.

**Comment by WASasquatch** [comment]
When updating ComfyUI, you often have to re-run requirements for custom nodes, to downgrade/upgrade modules.

**Comment by picobyte** [comment]
I tried this, but trying to find the middle way between the many outdated requirements file versions just breaks more custom nodes.

**Comment by WASasquatch** [comment]
Not outdated. Required. Comfy is the one ruining the ecosphere by running on bleeding edge python and dependencies that 90% of this stuff was not developed on. For example, Midas you are having issues with requires older transformers.

**Comment by picobyte** [comment]
Thanks, I think I'm getting near the solution. for this particular issue I added a __init__.py in the `ComfyUI/models/midas/intel-isl_MiDaS_master/midas/` directory. Then there were more issues, I had to disable many custom nodes, mentioned [here](https://github.com/melMass/comfy_mtb/issues/123#issuecomment-1807307932), 
Turned out to be related to tensorflow, and now [this](https://github.com/google-research/deduplicate-text-datasets/issues/33) seems to help (MTD custom node works again). By coincidence I had some of the package versions mentioned there, but not all. The error seemed related to [this](https://github.com/tensorflow/tensorflow/issues/62002).

**Comment by WASasquatch** [comment]
Clever fix on the midas model dir. Maybe this is a change with how hub works now (no longer providing py files set up)? Though that would be odd. 

And ohh, well that explains my MTB issues. Lol Thanks for the ping on that. I was just about to dig into that. 

Tensorflow hasn't had a good end of the year. I had a few issues with it too.

**Comment by DarkAlchy** [comment]
Did this ever get fixed as I just ran into this as missing and, frankly, I am unwilling to mess with python scripts that I then need to stash come update time.

**Comment by WASasquatch** [comment]
> Did this ever get fixed as I just ran into this as missing and, frankly, I am unwilling to mess with python scripts that I then need to stash come update time.

This fix is part of the Midas model downloaded from HF this unlikely to get any updates. And all it is is creating a blank `__init__.py` file, nothing in it, in that folder.

**Comment by DarkAlchy** [comment]
I was told Midas has been abandoned on Discord yesterday.  I did prefer Zoe but midas ran faster.

**Comment by WASasquatch** [comment]
Zoe is slow cause it's loading model each time, and it itself is not as fast. MiDaS is not abandoned. It has even newer versions, they just haven't been submitted to HF hub

**Comment by jsgreenawalt** [comment]
For me, the issue was that something (or someone...) had installed a package named midas:

>>> import midas
>>> dir(midas)
['Any', 'GasDetector', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'command_line', 'driver', 'util']
>>> quit()

This is numat / midas -- a python driver for a home automation device.  I uninstalled this 'midas' package and that solved it for me

**Comment by fernicar** [comment]
comfyui_controlnet_aux is using a different path to import this module in the other depth preprocessors, I just use modified it in my ComfyUI (StabilityMatrix version)
In your version of ComfyUI:
_YourPath_\ComfyUI\models\midas\intel-isl_MiDaS_master\hubconf.py

at lines: 5, 6 ,7 , 306 and 307
replace from: "from midas."
replace to: "from custom_midas_repo.midas."

now it should be able to find it, no need to restart ComfyUI to generate.

**Comment by WASasquatch** [comment]
This doesn't seem related to WAS-NS

**Comment by creeduk** [comment]
I added the fix this allowed it to go further it wanted to download the depth model dpt_large_384.pt - to folder ComfyUI\models\midas\checkpoints.

But now I get this error:
`Error occurred when executing MiDaS Depth Approximation:

Cannot find callable C:\ComfyUI\models\midas\checkpoints\dpt_large_384.pt in hubconf

File "C:\ComfyUI\execution.py", line 154, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\ComfyUI\execution.py", line 84, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\ComfyUI\execution.py", line 77, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 8561, in midas_approx
midas = torch.hub.load("intel-isl/MiDaS", midas_type, trust_repo=True)
File "C:\ComfyUI\comfyenv\lib\site-packages\torch\hub.py", line 566, in load
model = _load_local(repo_or_dir, model, *args, **kwargs)
File "C:\ComfyUI\comfyenv\lib\site-packages\torch\hub.py", line 594, in _load_local
entry = _load_entry_from_hubconf(hub_module, model)
File "C:\ComfyUI\comfyenv\lib\site-packages\torch\hub.py", line 348, in _load_entry_from_hubconf
raise RuntimeError(f'Cannot find callable {model} in hubconf')`

hubconf must be the intel_isl one which has not changed for a couple of years,

I tried with different models, tried a few py edits but could not figure out the issue, some disconnect between name and what is called maybe?

**Comment by WASasquatch** [comment]
Yes, Midas hasn't uploaded their new models to hugging face for
transformers support.

**Comment by wardenlee** [comment]
> ComfyUI (StabilityMatrix version) comfyui_controlnet_aux is using a different path to import this module like the other depth preprocessors, I just modified it. In your version of ComfyUI: _YourPath_\ComfyUI\models\midas\intel-isl_MiDaS_master\hubconf.py
> 
> at lines: 5, 6 ,7 , 306 and 307 replace from: "from midas." replace to: "from custom_midas_repo.midas."
> 
> now it should be able to find it, no need to restart ComfyUI to generate.

This is the most correct answer. Thanks ！

**Comment by Rochger** [comment]
> ComfyUI (StabilityMatrix version) comfyui_controlnet_aux is using a different path to import this module like the other depth preprocessors, I just modified it. In your version of ComfyUI: _YourPath_\ComfyUI\models\midas\intel-isl_MiDaS_master\hubconf.py
> 
> at lines: 5, 6 ,7 , 306 and 307 replace from: "from midas." replace to: "from custom_midas_repo.midas."
> 
> now it should be able to find it, no need to restart ComfyUI to generate.

best scheme!

**Comment by mrfrostycakes** [comment]
I am getting this error on my Midas Depth Node inside ComfyUI

"No module named 'midas.dpt_depth'"


`
# ComfyUI Error Report
## Error Details
- **Node Type:** MiDaS Model Loader
- **Exception Type:** ModuleNotFoundError
- **Exception Message:** No module named 'midas.dpt_depth'
## Stack Trace
```
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 8761, in load_midas_model
    midas = torch.hub.load("intel-isl/MiDaS", midas_model, trust_repo=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 570, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 596, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 108, in _import_module
    spec.loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 995, in exec_module

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\models\midas\intel-isl_MiDaS_master\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel

```
## System Information
- **ComfyUI Version:** v0.2.3-9-g0dbba9f
- **Arguments:** main.py
- **OS:** nt
- **Python Version:** 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170825216
  - **VRAM Free:** 15765340160
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-21 13:27:06,898 - root - INFO - Total VRAM 16375 MB, total RAM 65312 MB
2024-11-21 13:27:06,898 - root - INFO - pytorch version: 2.4.1+cu118
2024-11-21 13:27:06,898 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-21 13:27:06,899 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
2024-11-21 13:27:07,518 - root - INFO - Using pytorch cross attention
2024-11-21 13:27:08,573 - root - INFO - [Prompt Server] web root: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\web
2024-11-21 13:27:12,622 - ComfyUI_ParlerTTS.parler_tts.modeling_parler_tts - WARNING - Flash attention 2 is not installed
2024-11-21 13:27:13,890 - root - INFO - 
Import times for custom nodes:
2024-11-21 13:27:13,890 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-21 13:27:13,890 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-TextOverlay
2024-11-21 13:27:13,890 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-ParseQuestData
2024-11-21 13:27:13,890 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-UnixTimeStamp
2024-11-21 13:27:13,890 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-ParseLocationData
2024-11-21 13:27:13,890 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-SplitTextLine
2024-11-21 13:27:13,890 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-SaveImgPrompt
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_Noise
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_Eagleshadow
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-GeekyRemB
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode-main
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-VisualArea-Nodes
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\Comfy_KepListStuff
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\comfy-image-saver
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\rgthree-comfy
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
2024-11-21 13:27:13,891 - root - INFO -    0.0 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-11-21 13:27:13,891 - root - INFO -    0.2 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-21 13:27:13,891 - root - INFO -    0.3 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
2024-11-21 13:27:13,891 - root - INFO -    0.3 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_ParlerTTS
2024-11-21 13:27:13,891 - root - INFO -    0.3 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-Manager-main
2024-11-21 13:27:13,891 - root - INFO -    0.5 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-Allor
2024-11-21 13:27:13,892 - root - INFO -    0.7 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-11-21 13:27:13,892 - root - INFO -    1.1 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\ComfyUI-Griptape
2024-11-21 13:27:13,892 - root - INFO -    1.2 seconds: H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-11-21 13:27:13,892 - root - INFO - 
2024-11-21 13:27:13,899 - root - INFO - Starting server

2024-11-21 13:27:13,899 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-21 13:27:24,488 - root - INFO - got prompt
2024-11-21 13:27:24,635 - root - WARNING - WARNING: object supporting the buffer API required
2024-11-21 13:27:25,939 - root - ERROR - !!! Exception during processing !!! No module named 'midas.dpt_depth'
2024-11-21 13:27:25,941 - root - ERROR - Traceback (most recent call last):
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 8761, in load_midas_model
    midas = torch.hub.load("intel-isl/MiDaS", midas_model, trust_repo=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 570, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 596, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 108, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\models\midas\intel-isl_MiDaS_master\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'midas.dpt_depth'

2024-11-21 13:27:25,942 - root - INFO - Prompt executed in 1.37 seconds
2024-11-21 13:27:41,907 - root - INFO - got prompt
2024-11-21 13:27:42,056 - root - WARNING - WARNING: object supporting the buffer API required
2024-11-21 13:27:42,335 - root - ERROR - !!! Exception during processing !!! No module named 'midas.dpt_depth'
2024-11-21 13:27:42,335 - root - ERROR - Traceback (most recent call last):
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 8761, in load_midas_model
    midas = torch.hub.load("intel-isl/MiDaS", midas_model, trust_repo=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 570, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 596, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 108, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\models\midas\intel-isl_MiDaS_master\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'midas.dpt_depth'

2024-11-21 13:27:42,336 - root - INFO - Prompt executed in 0.34 seconds
2024-11-21 13:30:32,894 - root - INFO - got prompt
2024-11-21 13:30:33,041 - root - WARNING - WARNING: object supporting the buffer API required
2024-11-21 13:30:33,758 - root - ERROR - !!! Exception during processing !!! No module named 'midas.dpt_depth'
2024-11-21 13:30:33,759 - root - ERROR - Traceback (most recent call last):
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 8761, in load_midas_model
    midas = torch.hub.load("intel-isl/MiDaS", midas_model, trust_repo=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 570, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 596, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carey\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\hub.py", line 108, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "H:\Unity Projects\Mana Burn\generators\image_service\ComfyUI\models\midas\intel-isl_MiDaS_master\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'midas.dpt_depth'

2024-11-21 13:30:33,760 - root - INFO - Prompt executed in 0.78 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
`
