### ISSUE TITLE
BROKEN (was-node-suite-comfyui) does not work anymore import error

### ISSUE THREAD

**Issue by PhillipGimmi** [WASasquatch/was-node-suite-comfyui#298]
- I have  a Windows 10, 64 gigs of ram, 3080ti, 5950x, and i tried with both python 10.9  and 10.6.

- It no longer imports its not compatible with the latest comfyui

![Capture](https://github.com/WASasquatch/was-node-suite-comfyui/assets/104858994/a5167d27-39b0-491f-9f8a-59b4b51ee913)

**Comment by PhillipGimmi** [comment]
![Capture](https://github.com/WASasquatch/was-node-suite-comfyui/assets/104858994/20b39554-968b-46fc-8cc6-eb5c5312e0ff)
```Microsoft Windows [Version 10.0.19045.3693]
(c) Microsoft Corporation. All rights reserved.

D:\ComfyUI>python main.py
** ComfyUI start up time: 2023-12-06 20:58:34.079676

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['C:\\Users\\phill\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/WASasquatch/img2texture.git']

## Execute install/(de)activation script for 'D:\comfyui\custom_nodes\was-node-suite-comfyui'
 Collecting git+https://github.com/WASasquatch/img2texture.git
   Cloning https://github.com/WASasquatch/img2texture.git to c:\windows\temp\pip-req-build-hzan1ayw
[!]   Running command git clone --filter=blob:none --quiet https://github.com/WASasquatch/img2texture.git 'C:\Windows\Temp\pip-req-build-hzan1ayw'
   Resolved https://github.com/WASasquatch/img2texture.git to commit a546609a915caf1dcb84a15bf44b5b639ad924e6
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'done'
 Requirement already satisfied: pillow<10,>=9.2 in c:\users\phill\appdata\local\programs\python\python310\lib\site-packages (from img2texture==1.0.6) (9.4.0)

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\phill\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/WASasquatch/cstr']

## Execute install/(de)activation script for 'D:\comfyui\custom_nodes\was-node-suite-comfyui'
 Collecting git+https://github.com/WASasquatch/cstr
   Cloning https://github.com/WASasquatch/cstr to c:\windows\temp\pip-req-build-iyaun1kk
[!]   Running command git clone --filter=blob:none --quiet https://github.com/WASasquatch/cstr 'C:\Windows\Temp\pip-req-build-iyaun1kk'
   Resolved https://github.com/WASasquatch/cstr to commit 0520c29a18a7a869a6e5983861d6f7a4c86f8e9b
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'done'

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\phill\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', 'opencv-python-headless[ffmpeg]<=4.7.0.72']

## Execute install/(de)activation script for 'D:\comfyui\custom_nodes\was-node-suite-comfyui'
 Requirement already satisfied: opencv-python-headless<=4.7.0.72 in c:\users\phill\appdata\local\programs\python\python310\lib\site-packages (from opencv-python-headless[ffmpeg]<=4.7.0.72) (4.7.0.72)
 Requirement already satisfied: numpy>=1.21.2 in c:\users\phill\appdata\local\programs\python\python310\lib\site-packages (from opencv-python-headless<=4.7.0.72->opencv-python-headless[ffmpeg]<=4.7.0.72) (1.23.5)
[!] WARNING: opencv-python-headless 4.7.0.72 does not provide the extra 'ffmpeg'

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\phill\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/WASasquatch/ffmpy.git']

## Execute install/(de)activation script for 'D:\comfyui\custom_nodes\was-node-suite-comfyui'
 Collecting git+https://github.com/WASasquatch/ffmpy.git
   Cloning https://github.com/WASasquatch/ffmpy.git to c:\windows\temp\pip-req-build-i1hr9ku1
[!]   Running command git clone --filter=blob:none --quiet https://github.com/WASasquatch/ffmpy.git 'C:\Windows\Temp\pip-req-build-i1hr9ku1'
   Resolved https://github.com/WASasquatch/ffmpy.git to commit f000737698b387ffaeab7cd871b0e9185811230d
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'done'

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
  18.8 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 65481 MB
xformers version: 0.0.22.post4
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
Adding D:\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
Loaded efficiency nodes from D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from D:\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from D:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\control/control.py
Loaded AnimateDiff from D:\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from D:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from D:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V4.38.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
### Loading: ComfyUI-Inspire-Pack (V0.47.3)
### Loading: ComfyUI-Manager (V1.6.4)
### ComfyUI Revision: 1788 [2db86b46] | Released on '2023-12-06'
cpuinfo is already installed.
git is already installed.
moviepy is already installed.
cv2 is already installed.
skbuild is already installed.
typing is already installed.
diskcache is already installed.
llama_cpp is already installed.

Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-SVD\__init__.py", line 1, in <module>
    from .comfyui_svd import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ImportError: cannot import name 'NODE_CLASS_MAPPINGS' from 'ComfyUI-SVD.comfyui_svd' (D:\ComfyUI\custom_nodes\ComfyUI-SVD\comfyui_svd.py)

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-SVD module for custom nodes: cannot import name 'NODE_CLASS_MAPPINGS' from 'ComfyUI-SVD.comfyui_svd' (D:\ComfyUI\custom_nodes\ComfyUI-SVD\comfyui_svd.py)
Comfyroll Custom Nodes: Loaded
Using xformers cross attention
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'processing' from 'modules' (C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\modules.py)

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'processing' from 'modules' (C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\modules.py)
[comfy_mtb] | INFO -> loaded 59 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (3) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI\\custom_nodes\\ControlNet-LLLite-ComfyUI\\__init__.py'

Cannot import D:\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI\\custom_nodes\\ControlNet-LLLite-ComfyUI\\__init__.py'
Total VRAM 12287 MB, total RAM 65481 MB
xformers version: 0.0.22.post4
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Patching UNetModel.forward
UNetModel.forward has been successfully patched.
Downloading anime face detector...
Failed to download lbpcascade_animeface.xml so please download it in D:\ComfyUI\custom_nodes\IPAdapter-ComfyUI.
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI\\custom_nodes\\pfg-ComfyUI\\__init__.py'

Cannot import D:\ComfyUI\custom_nodes\pfg-ComfyUI module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI\\custom_nodes\\pfg-ComfyUI\\__init__.py'

[rgthree] Loaded 18 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

WAS Node Suite: Created default conf file at `D:\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`.
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\freeze.py", line 98, in run
    for line in freeze(
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\freeze.py", line 238, in from_dist
    req, comments = _get_editable_info(dist)
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\freeze.py", line 165, in _get_editable_info
    vcs_backend = vcs.get_backend_for_dir(location)
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir
    repo_path = vcs_backend.get_repository_root(location)
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\vcs\git.py", line 501, in get_repository_root
    r = cls.run_command(
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 650, in run_command
    return call_subprocess(
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 13709, in <module>
    if 'opencv-python' in packages() or 'opencv-python-headless' in packages():
  File "D:\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 333, in packages
    return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'freeze']).split()]
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\phill\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\phill\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-s', '-m', 'pip', 'freeze']' returned non-zero exit status 2.

Cannot import D:\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: Command '['C:\\Users\\phill\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-s', '-m', 'pip', 'freeze']' returned non-zero exit status 2.

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\ComfyUI\custom_nodes\chatbox_overlay.py
   0.0 seconds: D:\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_TiledIPAdapter
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: D:\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: D:\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: D:\ComfyUI\custom_nodes\FreeU_Advanced
   0.0 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\pfg-ComfyUI
   0.0 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: D:\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\ComfyUI-SVD
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\ComfyUI\custom_nodes\comfyui-dream-video-batches
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: D:\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: D:\ComfyUI\custom_nodes\comfy_mtb
   0.7 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\was-node-suite-comfyui
   0.8 seconds: D:\ComfyUI\custom_nodes\comfyui-art-venture

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
```

**Comment by WASasquatch** [comment]
The issue is checking packages on line 310 is not working on your manual
install of python which is interesting. I am not sure why that would be
happening. `pip freeze` is a common command. Maybe try removing the `'-s',`
part of the comment.

**Comment by jmanhype** [comment]
same issue please fix

**Comment by romaincherot** [comment]
Add `C:\Users\{youruser}\AppData\Roaming\Python\Python311\Scripts` to `PATH`, and next it worked for me (check the real path for you : username and Python version)

**Comment by rovo79** [comment]
Solved for my use-case: 
```
pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless numpy transformers
pip install opencv-python==4.7.0.72 numpy transformers
```

**Comment by LabMember01** [comment]
Same here 
![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/108751577/0435736d-812d-4a4a-8214-d01a3583ffd6)

**Comment by WASasquatch** [comment]
> Same here ![image](https://private-user-images.githubusercontent.com/108751577/294238618-0435736d-812d-4a4a-8214-d01a3583ffd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODYyNzMsIm5iZiI6MTcwNDM4NTk3MywicGF0aCI6Ii8xMDg3NTE1NzcvMjk0MjM4NjE4LTA0MzU3MzZkLTgxMmQtNGE0YS04MjE0LWQwMWEzNTgzZmZkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNjMyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDMzZDNhOTlkZThjYmZhOGM0ZjJiOGM4MTBhZTkxMDg4Y2I4MDQ1ZmM3OWMyYTc2MDk3YTBhYTQ2MGY2NzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KUB59IndizTJqkl6R4PoD_xj3ELYsFX-Z0k5X6BgswE)

Start your own topics and don't hijack other topics with irrelevant errors to OP. That doesn't help troubleshooting. 

You're getting that error because you did not install WAS-NS correctly, particularly Numba module.

**Comment by LabMember01** [comment]
> > Same here ![image](https://private-user-images.githubusercontent.com/108751577/294238618-0435736d-812d-4a4a-8214-d01a3583ffd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODYyNzMsIm5iZiI6MTcwNDM4NTk3MywicGF0aCI6Ii8xMDg3NTE1NzcvMjk0MjM4NjE4LTA0MzU3MzZkLTgxMmQtNGE0YS04MjE0LWQwMWEzNTgzZmZkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNjMyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDMzZDNhOTlkZThjYmZhOGM0ZjJiOGM4MTBhZTkxMDg4Y2I4MDQ1ZmM3OWMyYTc2MDk3YTBhYTQ2MGY2NzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KUB59IndizTJqkl6R4PoD_xj3ELYsFX-Z0k5X6BgswE)
> 
> Start your own topics and don't hijack other topics with irrelevant errors to OP. That doesn't help troubleshooting.
> 
> You're getting that error because you did not install WAS-NS correctly, particularly Numba module.

My bad, I didn't realize it wasn't the same issue.
I'll look in how to install WAS-NS, Numba...
