### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by NgoChingYee** [WASasquatch/was-node-suite-comfyui#300]
When I used lmage Pixelate node, I have this problem:

ERROR:root:Traceback (most recent call last):
  File "C:\Blender_ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Blender_ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Blender_ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Blender_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2489, in image_pixelate
    return ( self.pixel_art_batch(images, pixelation_size, num_colors, init_mode, max_iterations, 42,
  File "C:\Blender_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2495, in pixel_art_batch
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'

How can I fix it?

![image](https://github.com/WASasquatch/was-node-suite-comfyui/assets/136255531/8c1e22fe-7b88-4e31-9473-251e7a38ec5f)
![1702284648615](https://github.com/WASasquatch/was-node-suite-comfyui/assets/136255531/73332230-36a6-4447-a257-b946cd6f0fc5)

**Comment by WASasquatch** [comment]
Did you run the requirements file? `scikit-learn` package needs to be installed. `pip install scikit-learn`
