### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by p0mad** [WASasquatch/was-node-suite-comfyui#314]
Hi, I want to use WAS in the process for batch images on API... But i got this Error:

got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\Gen\Desktop\First\psl\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\Gen\Desktop\First\psl\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\Gen\Desktop\First\psl\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\Gen\Desktop\First\psl\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5816, in image_rembg
    for image in images:
TypeError: 'NoneType' object is not iterable

Would you please give me some hints? ( i dont want to use increamental image number for the input! Instead i want to have a loop to increase untill a number )

**Comment by p0mad** [comment]
@LoneOutpost 
I saw your commit, Could you please give me some hints on that?

Thanks
Best regards

**Comment by p0mad** [comment]
@WASasquatch 

It runs successfully on the UI but when it comes to the API in Code, It throws the error!

**Comment by HiProAI** [comment]
I just ran a workflow that I ran before last in February nothing has changed and I'm now getting this error 
'NoneType' object is not iterable
Which basically means it's not reading the first image in the batch which is the folder I point to nothing has changed same input folder that used to work before any ideas of what he issue is

**Comment by WAS-PlaiLabs** [comment]
Hard to say, but if it's NoneType, the entire list of images is none somehow, not that a first image is none. 

Mind sharing the workflow so I can try giving it a dir of images?
