### ISSUE TITLE
Cant load nodes

### ISSUE THREAD

**Issue by MCalerov** [WASasquatch/was-node-suite-comfyui#332]
This is the issue im facing: 

NotADirectoryError: [WinError 267] El nombre del directorio no es válido
Traceback (most recent call last):
  File "C:\Users\manue\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\manue\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "C:\Users\manue\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 13756, in <module>
    if 'opencv-python' in packages() or 'opencv-python-headless' in packages():
                          ^^^^^^^^^^
  File "C:\Users\manue\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 335, in packages
    return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'freeze']).split()]

**Comment by WASasquatch** [comment]
Something is wrong with your install. It's quoting

`C:\Users\manue\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui_init.py` instead of `C:\Users\manue\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\_init__.py` so files seem messed up.
