### ISSUE TITLE
Load Image Batch Error

### ISSUE THREAD

**Issue by Xenodimensional** [WASasquatch/was-node-suite-comfyui#333]
I think this is the part from the startup:

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5241, in INPUT_TYPES
    HDB = WASDatabase(WAS_HISTORY_DATABASE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 755, in __init__
    self.data = json.load(f)
                ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] An error occurred while retrieving information for the 'Text File History Loader' node.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 10390, in INPUT_TYPES
    HDB = WASDatabase(WAS_HISTORY_DATABASE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 755, in __init__
    self.data = json.load(f)
                ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] An error occurred while retrieving information for the 'Image History Loader' node.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5241, in INPUT_TYPES
    HDB = WASDatabase(WAS_HISTORY_DATABASE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 755, in __init__
    self.data = json.load(f)
                ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ERROR] An error occurred while retrieving information for the 'Text File History Loader' node.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 10390, in INPUT_TYPES
    HDB = WASDatabase(WAS_HISTORY_DATABASE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 755, in __init__
    self.data = json.load(f)
                ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

And then if I try to execute a prompt:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    obj = class_def()
          ^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5109, in __init__
    self.HDB = WASDatabase(WAS_HISTORY_DATABASE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 755, in __init__
    self.data = json.load(f)
                ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by WASasquatch** [comment]
Your config file is broke. May be error in config like not use double slashes for Windows paths. If you can't figure it out you can delete the file and let it generate a new one

**Comment by Xenodimensional** [comment]
Oh that is strange, I haven't modiefied any config files. Speaking of which, I don't suppose you could point me at the config you are referring to as when I do a search in the Comfy directory I have well over a thousand files named config and I can't see any obvious suspects in the root DIR etc. Many thanks!

**Comment by Xenodimensional** [comment]
I fixed it somehow (honestly amazed I didn't break something - touch wood!). Please consider it closed. 

I don't suppose you can fix other people's custom nodes? (jk!!)  Thank you very much for your nodes and your support. Both are very appreaciated!

**Comment by Xenodimensional** [comment]
I fixed it somehow (honestly amazed I didn't break something - touch wood!). I think it was deleting the WAS config file. Please consider this closed.

I don't suppose you can fix other people's custom nodes? (jk!!) Thank you very much for your nodes and your support. Both are very appreaciated!

**Comment by Xenodimensional** [comment]
I fixed it somehow (honestly amazed I didn't break something - touch wood!). I think it was deleting the WAS config file. Please consider this closed.

I don't suppose you can fix other people's custom nodes? (jk!!) Thank you very much for your nodes and your support. Both are very appreaciated!

**Comment by WASasquatch** [comment]
I seem to fix people's nodes all the time cause hard to use them otherwise when they freak out and nuke the place.
