### ISSUE TITLE
WAS Node Suite Warning: `ffmpeg_bin_path`

### ISSUE THREAD

**Issue by lunatico67** [WASasquatch/was-node-suite-comfyui#342]
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.

How can solve it?

**Comment by stephantual** [comment]
It's very my friend. I suspect you're on Windows:

- Stop comfy
- First you need ffmpeg - plently of options but https://www.gyan.dev/ffmpeg/builds/#git-master-builds offers a simple package. 
- Download ffmpeg-git-essentials.7z from that site
- Install 7z if you don't have it (https://7-zip.org/)
- Unzip the file you downloaded to any location, i place my in my C:/ drive.
- Edit \ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json
- In there find the line that says "    "ffmpeg_bin_path": "/path/to/ffmpeg",
- Change the path to your location you unziped the bins in - for example     "ffmpeg_bin_path": "C:\\ffmpeg_14_feb_2024\\bin",
- Make double sure you typed the path correctly (see above)
- Restart

Done!

**Comment by lunatico67** [comment]
> It's very my friend. I suspect you're on Windows:
> 
> * Stop comfy
> * First you need ffmpeg - plently of options but https://www.gyan.dev/ffmpeg/builds/#git-master-builds offers a simple package.
> * Download ffmpeg-git-essentials.7z from that site
> * Install 7z if you don't have it (https://7-zip.org/)
> * Unzip the file you downloaded to any location, i place my in my C:/ drive.
> * Edit \ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json
> * In there find the line that says "    "ffmpeg_bin_path": "/path/to/ffmpeg",
> * Change the path to your location you unziped the bins in - for example     "ffmpeg_bin_path": "C:\ffmpeg_14_feb_2024\bin",
> * Make double sure you typed the path correctly (see above)
> * Restart
> 
> Done!

Hi Stephan, sorry for the super delay in my reply, I just saw it now.
Thanks a million, problem solved, the error no longer appears. I had the ffmpeg package installed on my computer but I didn't have it addressed in was_suite_config.json as you showed me.

**Comment by optimbro** [comment]
This is how I did it:

`  "ffmpeg_bin_path": "C:\\Users\\Optim\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-7.0.1-full_build\\bin",
`

**Comment by WASasquatch** [comment]
If it's not set it attempts to use the system ffmpet, assuming path is in env path var. Which ffmpeg installer doesn't do, so most people get this issue.

**Comment by BccMaxwellc** [comment]
I have tried:
"ffmpeg_bin_path": "C:\\ComfyUI\\ComfyUI\\custom_nodes\\ffmpeg-2025-03-06-git-696ea1c223-essentials_build\\bin\\ffmpeg.exe",
and
"ffmpeg_bin_path": "C:\\ComfyUI\\ComfyUI\\custom_nodes\\ffmpeg-2025-03-06-git-696ea1c223-essentials_build\\bin",

But when running ComfyUI it seems to be looking for a __init__.py file.

Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\nodes.py", line 2147, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI\\ComfyUI\\custom_nodes\\ffmpeg-2025-03-06-git-696ea1c223-essentials_build\\__init__.py'

Cannot import C:\ComfyUI\ComfyUI\custom_nodes\ffmpeg-2025-03-06-git-696ea1c223-essentials_build module for custom nodes: [Errno 2] No such file or directory: 'C:\\ComfyUI\\ComfyUI\\custom_nodes\\ffmpeg-2025-03-06-git-696ea1c223-essentials_build\\__init__.py'

Any suggestions? Thanks :)
