### ISSUE TITLE
find and replace not working (needs seed input)

### ISSUE THREAD

**Issue by mrgreaper** [WASasquatch/was-node-suite-comfyui#36]
full error:
```
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  [Previous line repeated 5 more times]
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
TypeError: WAS_Search_and_Replace_Input.text_search_and_replace() missing 1 required positional argument: 'seed'
```

attaching the workflow and the lists.
I did try changing the find and replace to seed inputs, but that did not except the input from the seed node. also tried the example ones, and could not get either to work (same error)

[Wildcards.zip](https://github.com/WASasquatch/was-node-suite-comfyui/files/11181922/Wildcards.zip)

**Comment by WASasquatch** [comment]
Ah, yes, I removed the seed cause it no longer uses the old random.choice() method (cause it doesn't need it) but forgot to remove the seed from the function input. Should be fixed now.

**Comment by mrgreaper** [comment]
Incredibly fast fix and now working as expected :) thank you
