### ISSUE TITLE
Error occurred when executing BLIP Analyze Image

### ISSUE THREAD

**Issue by neovh34** [WASasquatch/was-node-suite-comfyui#369]
`![workflow(2)](https://github.com/WASasquatch/was-node-suite-comfyui/assets/114326672/bcd43dd5-415a-4e2d-b49b-d6a219f52cac)

The size of tensor a (6) must match the size of tensor b (36) at non-singleton dimension 0

  File "/opt/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/opt/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/opt/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 11097, in blip_caption_image
    caption = model.generate(tensor, sample=False, num_beams=6, max_length=74, min_length=20)
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_module.py", line 162, in generate
    outputs = self.text_decoder.generate(input_ids=input_ids,
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/transformers/generation/utils.py", line 1626, in generate
    return self.beam_search(
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/transformers/generation/utils.py", line 3068, in beam_search
    outputs = self(
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 886, in forward
    outputs = self.bert(
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 781, in forward
    encoder_outputs = self.encoder(
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 445, in forward
    layer_outputs = layer_module(
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 361, in forward
    cross_attention_outputs = self.crossattention(
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 277, in forward
    self_outputs = self.self(
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 178, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))`

**Comment by petercham** [comment]
> `![workflow(2)](https://private-user-images.githubusercontent.com/114326672/313758498-bcd43dd5-415a-4e2d-b49b-d6a219f52cac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Mjc4MjksIm5iZiI6MTcxMDkyNzUyOSwicGF0aCI6Ii8xMTQzMjY2NzIvMzEzNzU4NDk4LWJjZDQzZGQ1LTQxNWEtNGUyZC1iNDliLWQ2YTIxOWY1MmNhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwOTM4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzIzNGM4MDZlNDJlOGQyNWVjY2JiMjQzM2I1ZjZlMTNiYmRhMTZjN2EyOGM3MzRhZTE0ZDc5Yjg2YjRiNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5k2aw_Aj3l7O3y7wLpDk-BrWLQSyBLnpc8-ad1BTbwA)
> 
> The size of tensor a (6) must match the size of tensor b (36) at non-singleton dimension 0
> 
> File "/opt/ComfyUI/execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/opt/ComfyUI/execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/opt/ComfyUI/execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 11097, in blip_caption_image caption = model.generate(tensor, sample=False, num_beams=6, max_length=74, min_length=20) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_module.py", line 162, in generate outputs = self.text_decoder.generate(input_ids=input_ids, File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/transformers/generation/utils.py", line 1626, in generate return self.beam_search( File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/transformers/generation/utils.py", line 3068, in beam_search outputs = self( File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 886, in forward outputs = self.bert( File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 781, in forward encoder_outputs = self.encoder( File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 445, in forward layer_outputs = layer_module( File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 361, in forward cross_attention_outputs = self.crossattention( File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 277, in forward self_outputs = self.self( File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/opt/ComfyUI/custom_nodes/was-node-suite-comfyui/modules/BLIP/blip_med.py", line 178, in forward attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))`

I am experiencing the same issue, the problem happened yesterday after upgrading ComfyUI. The console outputs an error message:

WAS Node Suite Error: `transformers==4.26.1` is required for BLIP models. Please run the `C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\was-node- suite-comfyui\requirements.txt` through ComfyUI's ptyhon executable.
load checkpoint from //NAS65A682/SD-Share/models/Blip/model_base_caption_capfilt_large.pth
Exception during processing !!! Exception during processing !!!

**Comment by petercham** [comment]
I am experiencing the same issue, the problem happened yesterday after upgrading ComfyUI. The console outputs an error message:

WAS Node Suite Error: transformers==4.26.1 is required for BLIP models. Please run the C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\was-node- suite-comfyui\requirements.txt through ComfyUI's ptyhon executable.
load checkpoint from //NAS65A682/SD-Share/models/Blip/model_base_caption_capfilt_large.pth
Exception during processing !!! Exception during processing !!!

**Comment by 2053950** [comment]
The same issue in BLIP Amalyze Image on newly installed ComfyUI yesterday.
"The size of tensor a (6) must match the size of tensor b (36) at non-singleton dimension 0"
I installed the previous version of ComfyUI - it works.

**Comment by jfischoff** [comment]
I'm also getting this

**Comment by gonzalu** [comment]
Here is the full error I am getting: 

```
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 11097, in blip_caption_image
    caption = model.generate(tensor, sample=False, num_beams=6, max_length=74, min_length=20)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_module.py", line 162, in generate
    outputs = self.text_decoder.generate(input_ids=input_ids,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 1558, in generate
    return self.beam_search(
           ^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 2942, in beam_search
    outputs = self(
              ^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 886, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 781, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 445, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 361, in forward
    cross_attention_outputs = self.crossattention(
                              ^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 277, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\modules\BLIP\blip_med.py", line 178, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (6) must match the size of tensor b (36) at non-singleton dimension 0

Prompt executed in 0.06 seconds
```

**Comment by FOUR260** [comment]
I also have this problem, how should I solve it?
![Uploading 20240409012103.png…]()

**Comment by FOUR260** [comment]
I also have this problem, how should I solve it?
![20240409012103](https://github.com/WASasquatch/was-node-suite-comfyui/assets/112171490/95fa639e-6981-44ac-bf49-fc66d6309bf7)
