### ISSUE TITLE
Issue with BLIP Node Installation and Usage

### ISSUE THREAD

**Issue by lcolok** [WASasquatch/was-node-suite-comfyui#40]
I encountered the following issue while installing a BLIP node:
```
WAS NS: Installing BLIP dependencies...
WAS NS: Installing BLIP...
Using Legacy `transformImage()`
Traceback (most recent call last):
  File "F:\AI_research\Stable_Diffusion\ComfyUI\execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 4770, in blip_caption_image
    os.mkdir(blip_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\AI_research\\Stable_Diffusion\\ComfyUI\\ComfyUI\\models\\blip'
```
Later, I manually created a symbolic link, which solved the installation problem:
```
mklink /D F:\AI_research\Stable_Diffusion\ComfyUI\ComfyUI F:\AI_research\Stable_Diffusion\ComfyUI
```
However, it would be better if the path issue could be fixed or if the root path of the ComfyUI repo could be passed in manually when executing "python main.py".
Lastly, I encountered another issue when using BLIP:
```
Using Legacy `transformImaage()`
reshape position embedding from 196 to 576
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth
Traceback (most recent call last):
  File "F:\AI_research\Stable_Diffusion\ComfyUI\execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 4784, in blip_caption_image
    caption = model.generate(tensor, sample=False, num_beams=6, max_length=74, min_length=20)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\repos\BLIP\models\blip.py", line 159, in generate
    outputs = self.text_decoder.generate(input_ids=input_ids,
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\transformers\generation\utils.py", line 1490, in generate
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\transformers\generation\utils.py", line 2749, in beam_search
    decoder_attentions += (
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\repos\BLIP\models\med.py", line 886, in forward
    outputs = self.bert(
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\repos\BLIP\models\med.py", line 781, in forward
    encoder_outputs = self.encoder(
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\repos\BLIP\models\med.py", line 445, in forward
    layer_outputs = layer_module(
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\repos\BLIP\models\med.py", line 361, in forward
    cross_attention_outputs = self.crossattention(
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\repos\BLIP\models\med.py", line 277, in forward
    self_outputs = self.self(
  File "C:\ProgramData\Anaconda3\envs\comfyui\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI_research\Stable_Diffusion\ComfyUI\custom_nodes\was-node-suite-comfyui\repos\BLIP\models\med.py", line 178, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: The size of tensor a (6) must match the size of tensor b (36) at non-singleton dimension 0
```

**Comment by WASasquatch** [comment]
Are you by chance outdated? 5he new version checks to see if ComfyUI is already in the base path, and if if it is, doesn't add ConfyUI twice

**Comment by lcolok** [comment]
I encountered have been resolved and this new version works great! I believe that the WAS node plugin will definitely become an essential tool for ComfyUI users.

Thank you again for your great work!
