### ISSUE TITLE
Nodes not loading after ComfyUI Update

### ISSUE THREAD

**Issue by dreamlogic-X** [WASasquatch/was-node-suite-comfyui#406]
Hi there appears to be a problem with loading WAS nodes, as of  the update that happened 2024-05-25.  I'm now on ComfyUI: 5[b26da2](2024-05-27) now.

The error is as follows:

```
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 2398, in <module>
    from transformers import BlipProcessor, BlipForConditionalGeneration, BlipForQuestionAnswering
ImportError: cannot import name 'BlipProcessor' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)

Cannot import /notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui module for custom nodes: cannot import name 'BlipProcessor' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)
...
Import times for custom nodes:
...
   0.1 seconds (IMPORT FAILED): /notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui
...

```

Help would be appreciated to get this running again! Thank you.

**Comment by Pandasarethebest93** [comment]
At least you have it still appearing in comfyui. Mine gets (IMPORT FAILED): E:\Stability\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui,

**Comment by treeshark12** [comment]
Same here import failed, won't update.

**Comment by NeoAnthropocene** [comment]
Import fails after the last `ComfyUI: 2222[809cc8](2024-06-02)` update.
Currently, I disabled it ¯\_(ツ)_/¯

**Comment by Patrick-81** [comment]
Same here, none of custom nodes load. Happens after an update.
System is Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

**Comment by WASasquatch** [comment]
Reinstall the node requirements.

**Comment by mattymatty** [comment]
same here WASnodes do not even git clone any more. it fails

**Comment by mattymatty** [comment]
Fix: I had to turn off --listen before installing
