### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by Fr-Otaku** [WASasquatch/was-node-suite-comfyui#479]
Hi guys, i get this issue when trying to using dictionaries with the node. I've looking for a fix but can't find any solution. Btw thank you so much for all you work guys, you're precious <3

```2024-09-25 17:39:33,026 - root - ERROR - !!! Exception during processing !!! [Errno 13] Permission denied: 'D:\\AImatrix\\Data\\Packages\\ComfyUI\\dictionaries'
2024-09-25 17:39:33,027 - root - ERROR - Traceback (most recent call last):
  File "D:\AImatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AImatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AImatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AImatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 11077, in load_file
    file_list = self.TextFileLoader(file_path, label)
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 11100, in __init__
    self.load_file(file_path)
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 11111, in load_file
    with open(file_path, 'r', encoding="utf-8", newline='\n') as file:
```PermissionError: [Errno 13] Permission denied: 'D:\\AImatrix\\Data\\Packages\\ComfyUI\\dictionaries'
2024-09-25 17:39:33,028 - root - INFO - Prompt executed in 0.01 seconds
```

**Comment by WASasquatch** [comment]
Does python have write access to the file? Do you have the file open by another ComfyUI or process?

**Comment by Fr-Otaku** [comment]
> Does python have write access to the file? Do you have the file open by another ComfyUI or process? The error means it's either open already a locked by that process, or the user executing Python doesn't have read/write to the location.

I don't know, I used dictionaries a few months ago, but not anymore, I don't understand why. But that was before comfyui v2, maybe that's where it comes from, how can I check if write access is enabled?

**Comment by 135Arvin** [comment]
I have also encountered the same problem. I have tried to open and modify file permissions through administrator privileges, but still cannot solve it. Please find a solution. Thank you！！！

**Comment by WASasquatch** [comment]
That won't solve the problem, as the process you are running from (ConfyUI) is the one lacking permissions

**Comment by FVolral** [comment]
Hello, I have a similar issue. I'm using your nodes to load image sequences. You're not the only one offering this feature, and other alternative extensions are also breaking, so I assume you're all encountering a similar problem when accessing the disk, and it no longer works. For my part, this issue didn't exist a month or two ago. It started after I switched to a different version of ComfyUI that supports CUDA 12.4. Maybe that's related?

`
WARNING: [Errno 13] Permission denied: 'the/path/iam/using'
!!! Exception during processing !!! [Errno 13] Permission denied: 'the/path/iam/using'
Traceback (most recent call last):
  File "xxxx\ComfyUI_windows_portable_nvidia_cu124\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxx\ComfyUI_windows_portable_nvidia_cu124\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxx\ComfyUI_windows_portable_nvidia_cu124\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "xxxx\ComfyUI_windows_portable_nvidia_cu124\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxx\ComfyUI_windows_portable_nvidia_cu124\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\video.py", line 85, in load_image
    image, mask = img_from_path(image_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxx\ComfyUI_windows_portable_nvidia_cu124\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\video.py", line 163, in img_from_path
    img = Image.open(path)
          ^^^^^^^^^^^^^^^^
  File "xxxx\ComfyUI_windows_portable_nvidia_cu124\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3469, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'the/path/iam/using'
`

I anonymized some stuff. it seems related to the PIL version

**Comment by WASasquatch** [comment]
The error is pretty explanatory. Your python environment doesn't have
permission to write to disk.
