### ISSUE TITLE
Image Seamless Texture error -  img2tex() got an unexpected keyword argument 'return_result'

### ISSUE THREAD

**Issue by mr-asa** [WASasquatch/was-node-suite-comfyui#480]
![image](https://github.com/user-attachments/assets/051a1e70-0eda-4d54-8165-2d306e0962a1)

Hello. I haven’t opened one of my setups for a long time and now I’m faced with an error. 
What could be the problem and how can it be fixed?

```bash
!!! Exception during processing !!! img2tex() got an unexpected keyword argument 'return_result'
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 353, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 4635, in make_seamless
    seamless_images.append(pil2tensor(WTools.make_seamless(tensor2pil(image), blending, tiled, tiles)))
  File "F:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2186, in make_seamless
    texture = img2tex(src=image, dst=None, pct=blending, return_result=True)
TypeError: img2tex() got an unexpected keyword argument 'return_result'
```

**Comment by mr-asa** [comment]
oh, when highlighting the syntax I saw that for some reason the ComfyUI-0246 pack was also mentioned here, although it is not used in the assembly. When you turn it off there will be a slightly different error

```bash
got prompt
!!! Exception during processing !!! img2tex() got an unexpected keyword argument 'return_result'
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 4635, in make_seamless
    seamless_images.append(pil2tensor(WTools.make_seamless(tensor2pil(image), blending, tiled, tiles)))
  File "F:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 2186, in make_seamless
    texture = img2tex(src=image, dst=None, pct=blending, return_result=True)
TypeError: img2tex() got an unexpected keyword argument 'return_result'
```

**Comment by WASasquatch** [comment]
Do you have my custom fork of img2texture installed?

**Comment by mr-asa** [comment]
It hasn't been installed. Installed it and everything works. Thank you!
