### ISSUE TITLE
Text Find - object of type 'bool' has no len()

### ISSUE THREAD

**Issue by dirtyapenz** [WASasquatch/was-node-suite-comfyui#481]
FYI - Text Find is not working, error below.

# ComfyUI Error Report
## Error Details
- **Node Type:** Text Find
- **Exception Type:** TypeError
- **Exception Message:** object of type 'bool' has no len()
## Stack Trace
```
  File "/mnt/nvme2tb/github/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/mnt/nvme2tb/github/ComfyUI/execution.py", line 228, in get_output_data
    output = merge_result_data(results, obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/mnt/nvme2tb/github/ComfyUI/execution.py", line 175, in merge_result_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^

```

**Comment by WASasquatch** [comment]
Can you provide the full error? That's only part of a stack trace, but seems to be indicating you are passing nothing, a NoneType, to the node, so there is no value for length.

**Comment by mwoody450** [comment]
Same issue, even in this simple test workflow:
![image](https://github.com/user-attachments/assets/f66340d2-9b5d-41db-b8e2-2c65b23c5da9)

# ComfyUI Error Report
## Error Details
- **Node Type:** Text Find
- **Exception Type:** TypeError
- **Exception Message:** object of type 'bool' has no len()
## Stack Trace
```
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 228, in get_output_data
    output = merge_result_data(results, obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 175, in merge_result_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.3-25-gf82314f
- **Arguments:** ComfyUI\main.py --windows-standalone-build --front-end-version Comfy-Org/ComfyUI_frontend@latest --lowvram
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 11574181888
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-23 23:54:07,271 - root - INFO - Total VRAM 12282 MB, total RAM 65367 MB
2024-10-23 23:54:07,272 - root - INFO - pytorch version: 2.5.0+cu121
2024-10-23 23:54:07,272 - root - INFO - Set vram state to: LOW_VRAM
2024-10-23 23:54:07,272 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
2024-10-23 23:54:07,924 - root - INFO - Using pytorch cross attention
2024-10-23 23:54:08,689 - root - INFO - Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
2024-10-23 23:54:08,858 - root - INFO - [Prompt Server] web root: G:\AI\ComfyUI_windows_portable\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.21
2024-10-23 23:54:09,392 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-23 23:54:09,401 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-10-23 23:54:09,402 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-23 23:54:09,444 - root - INFO - Total VRAM 12282 MB, total RAM 65367 MB
2024-10-23 23:54:09,445 - root - INFO - pytorch version: 2.5.0+cu121
2024-10-23 23:54:09,446 - root - INFO - Set vram state to: LOW_VRAM
2024-10-23 23:54:09,446 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
2024-10-23 23:54:15,001 - root - INFO - 
Import times for custom nodes:
2024-10-23 23:54:15,001 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-23 23:54:15,001 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Lotus
2024-10-23 23:54:15,001 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
2024-10-23 23:54:15,002 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler
2024-10-23 23:54:15,002 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
2024-10-23 23:54:15,002 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\lora-info
2024-10-23 23:54:15,002 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption
2024-10-23 23:54:15,002 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-10-23 23:54:15,002 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-23 23:54:15,002 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-23 23:54:15,003 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-23 23:54:15,004 - root - INFO -    0.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper
2024-10-23 23:54:15,004 - root - INFO -    0.1 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-23 23:54:15,004 - root - INFO -    0.2 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depth-Pro
2024-10-23 23:54:15,004 - root - INFO -    0.2 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-10-23 23:54:15,004 - root - INFO -    0.6 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-23 23:54:15,004 - root - INFO -    1.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes
2024-10-23 23:54:15,004 - root - INFO -    1.0 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-23 23:54:15,004 - root - INFO -    1.1 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-23 23:54:15,004 - root - INFO -    1.4 seconds: G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes
2024-10-23 23:54:15,004 - root - INFO - 
2024-10-23 23:54:15,011 - root - INFO - Starting server

2024-10-23 23:54:15,012 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-23 23:54:22,381 - root - INFO - got prompt
2024-10-23 23:54:22,384 - root - ERROR - !!! Exception during processing !!! object of type 'bool' has no len()
2024-10-23 23:54:22,385 - root - ERROR - Traceback (most recent call last):
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 228, in get_output_data
    output = merge_result_data(results, obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 175, in merge_result_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()

2024-10-23 23:54:22,386 - root - INFO - Prompt executed in 0.00 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":4,"last_link_id":3,"nodes":[{"id":1,"type":"Text Find","pos":{"0":2309.9912109375,"1":-1012.4735717773438},"size":{"0":325,"1":100},"flags":{},"order":1,"mode":0,"inputs":[{"name":"text","type":"STRING","link":1,"widget":{"name":"text"}}],"outputs":[{"name":"found","type":"BOOLEAN","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"Text Find"},"widgets_values":["","text",""]},{"id":2,"type":"Boolean To Text","pos":{"0":2309.9912109375,"1":-862.4735717773438},"size":{"0":325,"1":50},"flags":{},"order":2,"mode":0,"inputs":[{"name":"boolean","type":"BOOLEAN","link":2,"widget":{"name":"boolean"}}],"outputs":[{"name":"STRING","type":"STRING","links":[3],"slot_index":0}],"properties":{"Node name for S&R":"Boolean To Text"},"widgets_values":[false]},{"id":3,"type":"Text Multiline","pos":{"0":2059.9912109375,"1":-1012.4735717773438},"size":{"0":225,"1":200},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"STRING","type":"STRING","links":[1],"slot_index":0}],"properties":{"Node name for S&R":"Text Multiline"},"widgets_values":["Test Text\n\n\ntest text"]},{"id":4,"type":"ShowText|pysssss","pos":{"0":2659.9912109375,"1":-1012.4735717773438},"size":{"0":325,"1":200},"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":3,"widget":{"name":"text"}}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]}],"links":[[1,3,0,1,0,"STRING"],[2,1,0,2,0,"BOOLEAN"],[3,2,0,4,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.090909090909092,"offset":[-1461.4077838234696,1391.9735646340307]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
