### ISSUE TITLE
ComfyUI frontend never stops "loading"

### ISSUE THREAD

**Issue by theredwillow** [WASasquatch/was-node-suite-comfyui#494]
A few days ago, I tried my first Flux workflow with a tutorial (I believe it was [this one](https://www.youtube.com/watch?v=DdSe5knj4k8)). I don't know if that's relevant or not.

After restarting, the frontend started loading and never stopped. The wheel / circle / loading icon never went away.
![image](https://github.com/user-attachments/assets/2037f166-ee4d-4672-92c7-d7f6f5d967ed)

I can manually delete the loading element from dev tools and get it to load workflows and such, but I haven't tested it extensively.

I get this error in my console.

```
hook.js:608 TypeError: (output ?? []).map is not a function
    at ComfyNodeDefImpl.transformOutputSpec (nodeDefStore.ts:180:35)
    at new ComfyNodeDefImpl (nodeDefStore.ts:174:36)
    at Proxy.updateNodeDefs (nodeDefStore.ts:306:29)
    at Proxy.wrappedAction (pinia.mjs:1405:26)
    at ComfyApp.updateVueAppNodeDefs (app.ts:1963:18)
    at ComfyApp.registerNodes (app.ts:1978:12)
    at async ComfyApp.registerNodes (workflow-component.js:328:2)
    at async ComfyApp.setup (app.ts:1871:5)
    at async GraphCanvas.vue:189:9
```

There are other errors, but I don't think they're related.

ComfyUI's Frontend repo says to try with the no custom nodes flag before submitting a bug ticket. So I did that and it worked. So I went through a process of manually removing nodes until it worked again without the flag.

This was-node-suite-comfyui folder was the one that seemed to break it. I may not have tested enough, perhaps it's related to custom nodes competing for something, but I wanted to submit a ticket somewhere.

**Comment by WASasquatch** [comment]
WAS-NS has no front-end modifications of any sort. So it wouldn't be an
issue with this custom node.

**Comment by gothxx** [comment]
encount the same problem,

**Comment by gothxx** [comment]
clean an reinstall from git, it's work now!
