### ISSUE TITLE
Getting [Errno 13] error when trying to import styles.

### ISSUE THREAD

**Issue by Ryuukarasu** [WASasquatch/was-node-suite-comfyui#504]
I'm using Stability Matrix and trying to link ComfyUI to the styles of my stable diffusion installation. Every time I turn it on I get the error "[Errno 13]" error saying I don't have privileges to access that file. This is the section of code in the terminal talking about it.

```
WAS Node Suite: Importing styles from `C:\Users\epbra\Documents\AI\Stability Matrix\Packages\Stable Diffusion WebUI reForge`.
Traceback (most recent call last):
  File "C:\Users\epbra\Documents\AI\Stability Matrix\Packages\ComfyUI\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\epbra\Documents\AI\Stability Matrix\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "C:\Users\epbra\Documents\AI\Stability Matrix\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 305, in <module>
    with open(webui_styles_file, "r", encoding="utf-8-sig", newline='') as file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\epbra\\Documents\\AI\\Stability Matrix\\Packages\\Stable Diffusion WebUI reForge'

Cannot import C:\Users\epbra\Documents\AI\Stability Matrix\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: [Errno 13] Permission denied: 'C:\\Users\\epbra\\Documents\\AI\\Stability Matrix\\Packages\\Stable Diffusion WebUI reForge'
```

**Comment by carolekon** [comment]
in  \was-node-suite-comfyui\was_suite_config.json under webui_styles you need to include the .csv file in the path, like this

"webui_styles": "C:\\Users\\epbra\\Documents\\AI\\Stability Matrix\\Packages\\Stable Diffusion WebUI reForge\\styles.csv"

I think you just got the path in there

**Comment by WASasquatch** [comment]
Looks like you are trying to access another pythons files, and likely don't have permission from the Comfy environments python executable. You'll need to change permissions
