### ISSUE TITLE
Import fail

### ISSUE THREAD

**Issue by Opeth66** [WASasquatch/was-node-suite-comfyui#508]
I am getting import failed with v0.2.7 of comfy ui

**Comment by aphaits** [comment]
Getting import failed with newest v0.3.5

**Comment by WASasquatch** [comment]
Please provide useful information such as your ComfyUI logs which should contain any errors. I don't have your system, so I can't reproduce, so I need specifics.

**Comment by aphaits** [comment]
F:\StableDiffusion\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Adding extra search path checkpoints F:/StableDiffusion/Models/Checkpoints
Adding extra search path configs F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\path\to\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae F:/StableDiffusion/Models/VAE
Adding extra search path loras F:/StableDiffusion/Models/LORAs
Adding extra search path upscale_models F:/StableDiffusion/Models/Upscale
Adding extra search path embeddings F:/StableDiffusion/Models/Embeddings
Adding extra search path hypernetworks F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\path\to\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet F:/StableDiffusion/Models/ControlNet
Adding extra search path facerestore_models F:/StableDiffusion/Models/Face_Restore
Adding extra search path facedetection F:/StableDiffusion/Models/FaceDetection
Adding extra search path clip_vision F:/StableDiffusion/Models/Clip_Vision
Adding extra search path clip F:/StableDiffusion/Models/Clip
Adding extra search path style_models F:/StableDiffusion/Models/Style_Models
Adding extra search path unet F:/StableDiffusion/Models/Unet
Adding extra search path ipadapter F:/StableDiffusion/Models/IP_Adapter
Adding extra search path insightface F:/StableDiffusion/Models/insightface
Adding extra search path instantid F:/StableDiffusion/Models/InstantID
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-01-20 01:31:12.127
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI
** User directory: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   7.2 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65465 MB
pytorch version: 2.2.2+cu121
xformers version: 0.0.25.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
Using xformers attention
[Prompt Server] web root: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\web
Web extensions folder found at F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Adding F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V8.3.1)
### Loading: ComfyUI-Impact-Pack (V8.3.1)
Loaded ImpactPack nodes from F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: AMD Ryzen 7 3700X 8-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 2070 SUPER
[Crystools INFO] NVIDIA Driver: 566.36
F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
2025-01-20 01:31:34.916639: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
From F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

### Loading: ComfyUI-Impact-Pack (V8.3.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.9.1)
Total VRAM 8192 MB, total RAM 65465 MB
pytorch version: 2.2.2+cu121
xformers version: 0.0.25.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
theUpsiders Logic Nodes: Loaded
### Loading: ComfyUI-Manager (V3.7.4)
### ComfyUI Version: v0.3.10-53-g3aaabb12 | Released on '2025-01-14'
------------------------------------------
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
### N-Suite Revision: ae7cc848
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.37
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Current version of moviepy: 1.0.3
Current version of cv2: 4.8.1
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://api.comfy.org/nodes?page=1&limit=1000Current version of skbuild: 0.17.6
Version of typing: Not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.26+cu121
Current version of timm: 0.9.12
F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 2.0.0 (you have 1.4.16). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

ComfyUI-Portrait-Maker : ### : Check dependencies
ComfyUI-Portrait-Maker : F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\requirements.txt
ComfyUI-Portrait-Maker : aliyun-python-sdk-core-v3==2.13.10

ComfyUI-Portrait-Maker : opencv-python

ComfyUI-Portrait-Maker : tensorflow-cpu

ComfyUI-Portrait-Maker : tensorflow

ComfyUI-Portrait-Maker : onnx

ComfyUI-Portrait-Maker : onnxruntime

ComfyUI-Portrait-Maker : modelscope

ComfyUI-Portrait-Maker : scikit-image

ComfyUI-Portrait-Maker : matplotlib

ComfyUI-Portrait-Maker : insightface

ComfyUI-Portrait-Maker : diffusers==0.18.2

ComfyUI-Portrait-Maker : sentencepiece
2025-01-20 01:31:48,684 - modelscope - INFO - PyTorch version 2.2.2+cu121 Found.
2025-01-20 01:31:48,686 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2025-01-20 01:31:48,686 - modelscope - INFO - Loading ast index from C:\Users\Aphaits\.cache\modelscope\ast_indexer
2025-01-20 01:31:48,827 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 098532baffa015075d2247d6987e7413 and a total number of 964 components indexed
PyTorch version 2.2.2+cu121 available.
TensorFlow version 2.15.0 available.
Start Setting weights
[ReActor] - STATUS - Running v0.5.2-b1 in ComfyUI
Torch version: 2.2.2+cu121
 [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes?page=1&limit=1000
nightly_channel: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/cache
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
### [START] ComfyUI AlekPet Nodes v1.0.41 ###
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode, ChatGLM4InstructNode, ChatGLM4InstructMediaNode [Loading]
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading] Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading]

Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> PoseNode: PoseNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
[comfy_mtb] | INFO -> loaded 96 nodes successfuly
Traceback (most recent call last):
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2106, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node\__init__.py", line 1, in <module>
    from rembg import remove
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\rembg\bg.py", line 16, in <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pymatting\__init__.py", line 2, in <module>
    from pymatting.util import *
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pymatting\util\__init__.py", line 2, in <module>
    from pymatting.util.kdtree import KDTree, knn
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pymatting\util\kdtree.py", line 2, in <module>
    from numba import njit, prange
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.25 or less")
ImportError: Numba needs NumPy 1.25 or less

Cannot import F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node module for custom nodes: Numba needs NumPy 1.25 or less

[rgthree-comfy] Loaded 43 exciting nodes. 🎉

Traceback (most recent call last):
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2106, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "F:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.25 or less")
ImportError: Numba needs NumPy 1.25 or less

Cannot import F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: Numba needs NumPy 1.25 or less

Import times for custom nodes:
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\loadImageWithSubfolders.py
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Fans
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-video-batches
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds (IMPORT FAILED): F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds (IMPORT FAILED): F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node
   0.1 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
   0.1 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.1 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-project
   0.2 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.3 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.4 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.5 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus
   1.2 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   1.4 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.8 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   2.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker
   2.0 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   3.9 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
  11.3 seconds: F:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM

Starting server

To see the GUI go to: http://127.0.0.1:8188
