### ISSUE TITLE
Last update from Comfy UI block the loading of WAS SUITE

### ISSUE THREAD

**Issue by MattRM2** [WASasquatch/was-node-suite-comfyui#527]
Hi, could you do something about this please ?
Thank you

``` Traceback (most recent call last):
  File "E:\00_ComfyUI\ComfyUI\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less

Cannot import E:\00_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: Numba needs NumPy 1.24 or less ```

**Comment by MattRM2** [comment]
Solved, I forced the last Numpy and the 1.24 into my embedded python :)
