### ISSUE TITLE
ffmpeg_bin_path breaks loading of WAS nodes

### ISSUE THREAD

**Issue by polarsky89** [WASasquatch/was-node-suite-comfyui#63]
I've downloaded full ffmpeg package and pointed the 'bin' directrory in was_suite_config, also added it to Path. When the directory is present in config i get the error:
WAS Node Suite Running At: C:\Grafika\AI_GEN\TOOLS\ComfyUI-master\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py
WAS Node Suite Running From: C:\Grafika\AI_GEN\TOOLS\ComfyUI-master\custom_nodes\was-node-suite-comfyui
Invalid \escape: line 11 column 27 (char 723)
Traceback (most recent call last):
  File "C:\Grafika\AI_GEN\TOOLS\ComfyUI-master\nodes.py", line 1269, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Grafika\AI_GEN\TOOLS\ComfyUI-master\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "C:\Grafika\AI_GEN\TOOLS\ComfyUI-master\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 166, in <module>
    if not was_config.__contains__(sett_):
AttributeError: 'bool' object has no attribute '__contains__'

Cannot import C:\Grafika\AI_GEN\TOOLS\ComfyUI-master\custom_nodes\was-node-suite-comfyui module for custom nodes: 'bool' object has no attribute '__contains__'
Starting server

To see the GUI go to: http://127.0.0.1:8188

As soon as I leave ffmpeg bin dir empty WAS nodes are loaded

**Comment by WASasquatch** [comment]
Looks like you're saving the file in the wrong encoding our making a syntax error.
