### ISSUE TITLE
error when using Image Crop Face

### ISSUE THREAD

**Issue by GregorioBrc** [WASasquatch/was-node-suite-comfyui#75]
I'm using colab and I used a framework to rule out that I was doing something wrong and it still fails

![imagen](https://github.com/WASasquatch/was-node-suite-comfyui/assets/93452240/d808d4c4-fa2e-421c-b1d7-8a47b281c296)

console error message:

Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "/content/ComfyUI/execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "/content/ComfyUI/execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 2325, in image_crop_face
    return self.crop_face(tensor2pil(image), cascade_xml, crop_padding_factor, use_fr)
  File "/content/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 2368, in crop_face
    cstr("Face found with:", os.path.basename(cascade)).msg.print()
TypeError: cstr.__new__() takes 2 positional arguments but 3 were given

**Comment by WASasquatch** [comment]
That should be patched now.
