### ISSUE TITLE
AUTOMATIC1111 WebUI Styles

### ISSUE THREAD

**Issue by wolf95985** [WASasquatch/was-node-suite-comfyui#88]
When I Import AUTOMATIC1111 WebUI Styles, the following error is thrown in console:
```
Traceback (most recent call last):
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1384, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 279, in <module>
    styles[line[name]] = {"prompt": line['prompt'], "negative_prompt": line['negative_prompt']}
KeyError: 'name'

Cannot import H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: 'name'

Import times for custom nodes:
   0.2 seconds (IMPORT FAILED): H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   7.9 seconds: H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
```
Am I doing something wrong?

**Comment by WASasquatch** [comment]
Can I see the the top of your style cvs import file (from like a text editor)? I was having issues with a CVS parser, and basically wrote my own, so handling edge cases where there is different formatting

**Comment by wolf95985** [comment]
Thank you for your work, after upgrading to the new version the problem has been solved

**Comment by WASasquatch** [comment]
Sweet, good to hear.
